### ISSUE TITLE
Laravel 4.2 support

### ISSUE THREAD

**Issue by briedis** [spatie/laravel-newsletter#1]
I currently have a project with L4, and would really like to use this package. I think that it shouldn't be a problem to make it compatible, just add another service provider.

**Comment by gpluess** [comment]
+1 for 4.2 support :smile:

**Comment by freekmurze** [comment]
As I don't need this myself, adding L4 support is kinda low priority. But I'll accept a good pull request any day.

Pro-tip: upgrade to L5: it's awesome :)

**Comment by briedis** [comment]
Yeah I know L5 is cool, I  have multiple projects with it, even migrated one :)

Ok, I'll try to make a service provider for L4.

Are there any specific L5 features used in the package (except the L5 service provider) ?

**Comment by freekmurze** [comment]
Cool, thanks!

I don't think there are much L5 specific things being used at the moment. Maybe a L5-style `config('blabla')`instead of a L4 `Config::get('blablabla')`. If you encouter such things just change it to L4-style. Be sure to test it all out before submitting the pull request.

**Comment by freekmurze** [comment]
I'll close this issue for now, if you need L4 support feel free to submit a PR.
