### ISSUE TITLE
How to set 'status' to 'pending'

### ISSUE THREAD

**Issue by webinfinita** [spatie/laravel-newsletter#104]
First of all, thank you for this and all your other packages are really usefull!

When subscribing a user, there is no way to set a double opt-in, I saw is hardcoded to 'subscribed' in the source code. 

Would be nice to allow double opt-in because: 'This process eliminates many of the "bad" email addresses that get entered into a system (typos or incorrect email addresses) and also protects against instances where somebody may be taking "revenge" on another person by using their email address to sign up for numerous email marketing lists.' comm100.com

Thank you again for this package!

**Comment by morloderex** [comment]
@webinfinita You should be able to override the default option of subscribe. With the 4 parameter of the `subscribe` method sense it does an array_merge().

**Comment by webinfinita** [comment]
Thank you!
