### ISSUE TITLE
Nothing being sent to MailChimp

### ISSUE THREAD

**Issue by DouglasEvans** [spatie/laravel-newsletter#108]
Hello,

I'm having difficulty subscribing any emails to Mailchimp. I have installed everything correctly and added in the appropriate service provider and facade in the `config\app.php` file, imported the `laravel-newsletter.php` file and this my code in the `store` function in my controller that I am using to test:

```
Newsletter::subscribe('john.smith@gmail.com');
flash('Thank you, your email has been added.', 'success');
return redirect()->back();
```

When I click the submit button I am redirected back with the flash message, but nothing appears in Mailchimp. I have confirmed checking on the API Keys page that the requests are not being processed.

I have added the MailChimp API key and associated list ID to my `.env` file but I am not sure that they are being read correctly because if I delete them entirely from the `.env` file no errors are thrown on the website, and no errors appear in `laravel.log`.

The bizarre thing though is that I'm using this same package on another website and it is functioning just fine, the only difference as far as I can tell (aside from the API key & list id) is my older site uses version 3.6, while this site is using 3.7.

Thank you.

**Comment by freekmurze** [comment]
What happens if you execute 

```php
Newsletter::subscribe('john.smith@gmail.com');
```

in a tinker session?

**Comment by DouglasEvans** [comment]
It returns `false` and nothing else.

**Comment by freekmurze** [comment]
What's the output of 

```
Newsletter::subscribe('john.smith@gmail.com');
Newsletter::getLastError();
```

in a tinker session?

**Comment by DouglasEvans** [comment]
I receive the following: `Unknown error, call getLastReponse() to find out what happened.`

I am doing this on my localhost, however my other Laravel project that is working is also on my localhost. I've been trying to push something to a development URL to see if that changes anything.

**Comment by DouglasEvans** [comment]
Pushing to a development URL on an actual server seems to have solved the issue, I can add emails and it's pushing them through to Mailchimp just fine. I don't understand why one of my localhost projects works and this one doesn't, but the problem seems to be fixed.

**Comment by MuzammilRafay** [comment]
i have same issue here my i have imported all things which is needed but still not response in my listing of mail chimp
and in tinker i have same issue "Unknown error, call getLastResponse() to find out what happened."

**Comment by chenshuiluke** [comment]
@DouglasEvans 

I was also getting that error on my local environment. I just had to set `ssl` in newsletter.php to false:

```
    /*
     * If you're having trouble with https connections, set this to false.
     */
    'ssl' => false,
```

**Comment by VentoMichael** [comment]
Hi it don't send into mailchimp but i have no error.
