### ISSUE TITLE
I'm getting errors when trying to update to Laravel 5.5

### ISSUE THREAD

**Issue by antonijap** [spatie/laravel-newsletter#118]
I get this:

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.5.3
    - Conclusion: don't install laravel/framework v5.5.3
    - Installation request for spatie/laravel-newsletter ^3.7 -> satisfiable by spatie/laravel-newsletter[3.7.0].
    - Conclusion: don't install laravel/framework v5.5.2
    - Conclusion: don't install laravel/framework v5.5.1
    - spatie/laravel-newsletter 3.7.0 requires illuminate/support ~5.1.0|~5.2.0|~5.3.0|~5.4.0 -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].

Is there some workaround?

**Comment by freekmurze** [comment]
Use v4 of this package.
