### ISSUE TITLE
Laravel 5.5 Invalid MailChimp API key `` supplied.

### ISSUE THREAD

**Issue by Wolrab1** [spatie/laravel-newsletter#119]
I've got a fresh install of Laravel 5.5, I've pulled in Laravel Newsletter via composer and after publishing the Newsletter config I add the following variables to my .env file.

MAILCHIMP_APIKEY=MY_API_KEY
MAILCHIMP_LIST_ID=MY_LIST_ID

Values are actual keys / ID's from Mailchimp and when trying to use the Newsletter::getApi() or Newsletter::subscribe('test@test.com');

I get the following:

> Exception
> Invalid MailChimp API key `` supplied.

I've tried removing the env variables from the Newsletter config and hard coded the the API key and list ID but I'm still get the same issue.

My config:

```
<?php

return [

        'apiKey' => env('MAILCHIMP_APIKEY'),

        'defaultListName' => 'subscribers',

        'lists' => [

            'subscribers' => [
                'id' => env('MAILCHIMP_LIST_ID'),
            ],
        ],

        'ssl' => true,
];

```
I've tried to also dd(config('laravel-newsletter')) but I get nothing.

Can anyone point me in the right direction?

**Comment by freekmurze** [comment]
Try running `php artisan cache:clear`. If that doesn't help, try installing the package in a vanilla Laravel app to rule out something project specific is causing you troubles.

**Comment by connor11528** [comment]
```
$ php artisan config:clear
$ php artisan config:cache
```

did the trick for me when I ran into this error in Laravel 5.5
