### ISSUE TITLE
Class laravel-newsletter does not exist

### ISSUE THREAD

**Issue by dixitchopra** [spatie/laravel-newsletter#120]
I am getting the following error while using the library.

ReflectionException in Container.php line 741:
Class laravel-newsletter does not exist

**Comment by freekmurze** [comment]
This is probably due to the fact that you didn't follow are installation steps. Or maybe there's something in your current project causing troubles. Try installing the package in a vanilla Laravel app.

**Comment by dixitchopra** [comment]
It gives me, "Nothing to publish for tag []." when I try to publish newsletter.php file in config.

**Comment by freekmurze** [comment]
Are you caching your config? In that case run `php artisan cache:clear` and try again.

**Comment by Mohib1992** [comment]
i did but still error exists.Btw im using  spatie/laravel-newsletter:3.7

**Comment by achilles03anil** [comment]
I m having the same error  using spatie/laravel-newsletter:3.7

**Comment by tarturek** [comment]
delete all file in /bootstrap/cache
