### ISSUE TITLE
Nothing to publish for tag [] when I publish in config file

### ISSUE THREAD

**Issue by dixitchopra** [spatie/laravel-newsletter#121]
It gives me an error - "Nothing to publish for tag []." when I try to publish the newsletter.php file in config. Please check the screenshot.

![screen shot 2017-09-16 at 1 49 40 pm](https://user-images.githubusercontent.com/1587610/30510676-f7ed45de-9ae5-11e7-96fb-95624c4863cb.png)

**Comment by freekmurze** [comment]
Try installing the package in a vanilla Laravel app.

**Comment by freekmurze** [comment]
Run `php artisan config:clear` and try publishing the assets again.

**Comment by bilal-hanif** [comment]
`php artisan config:clear` does not fixes the Issue.

**Comment by introwit** [comment]
Hi :) From your screenshot I can see that package wasn't discovered, so the service provider isn't registered. Register the service provider in the `config/app.php` file and try again, it will work :)

**Comment by bilal-hanif** [comment]
You need to add this line to `config/app.php`  in `'provider'=>[...` 
`Spatie\Newsletter\NewsletterServiceProvider::class,`

This should be mentioned in installation guide for less experienced fellows. :)

**Comment by introwit** [comment]
@bilal-hanif we only support Laravel 5.5 which automatically does this for you. But it seems there were some problems with the composer & project installation itself as visible in the screenshot which might have broke the things :)

**Comment by bilal-hanif** [comment]
@introwit Then this should definitely be mentioned in Readme. For now it says 

> package provides an easy way to integrate MailChimp with Laravel 5. Behind the scenes v3 for the MailChimp API is used. 

Which does not gives clear indication :)
