### ISSUE TITLE
Call to undefined method subscribeOrUpdate()

### ISSUE THREAD

**Issue by cubet-rahul** [spatie/laravel-newsletter#124]
I have an issue this package while using it in laravel 5.2

//app.php
'providers' => [
        
        Spatie\Newsletter\NewsletterServiceProvider::class,
    ],

'aliases' => [

        'Newsletter' => Spatie\Newsletter\NewsletterFacade::class,
    ],

in my  controller file.

use Newsletter;

Newsletter::subscribeOrUpdate('sample@gmail.com');

Error: 
FatalErrorException in Facade.php line 217:
Call to undefined method Spatie\Newsletter\Newsletter::subscribeOrUpdate()

**Comment by freekmurze** [comment]
We don't support L5.2 anymore.

Make sure you use the right version of the package and look at the right version of the documentation.
