### ISSUE TITLE
Can't install on Laravel 5.4

### ISSUE THREAD

**Issue by poncianodiego** [spatie/laravel-newsletter#128]
Error message when running `composer require spatie/laravel-newsletter`.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for spatie/laravel-newsletter ^4.1 -> satisfiable by spatie/laravel-newsletter[4.1.0].
    - Conclusion: remove laravel/framework v5.4.36
    - Conclusion: don't install laravel/framework v5.4.36
    - spatie/laravel-newsletter 4.1.0 requires illuminate/support ~5.5.0 -> satisfiable by illuminate/support[v5.5.0, v5.5.16, v5.5.17, v5.5.2].
    - don't install illuminate/support v5.5.0|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.16|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.17|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.2|don't install laravel/framework v5.4.36
    - Installation request for laravel/framework (locked at v5.4.36, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.36].
```
I tried to install via composer.json and composer update but the same issue appears.

I also tried to remove all vendor files run composer install and composer require spatie/laravel-newsletter again but the same issue shows up.

I see other issues like this in packages from this account but I see no clear resolution or explanation of the issue.

I'm running php 7.1.1 in my CLI.

Thanks for any help.

**Comment by freekmurze** [comment]
The latest version only has support for Laravel 5.5. Try installing v3 of the package.

**Comment by poncianodiego** [comment]
Ah thanks for clarifying I did notice that by looking closely to the logs. This is not clear in the readme: "This package provides an easy way to integrate MailChimp with Laravel 5." Anyone can assume is for any 5.* laravel version.

**Comment by freekmurze** [comment]
The requirements for a package can always be checked in `composer.json`. But I'll remove that "5" from the readme.

**Comment by nickforbizz** [comment]
Problem 1
    - Installation request for spatie/laravel-newsletter ^4.3 -> satisfiable by spatie/laravel-newsletter[4.3.0].
    - Conclusion: remove laravel/framework v5.7.9
    - Conclusion: don't install laravel/framework v5.7.9
    - spatie/laravel-newsletter 4.3.0 requires illuminate/support ~5.8.0 -> satisfiable by illuminate/support[5.8.x-dev, v5.8.0, v5.8.2, v5.8.3], laravel/framework[5.8.x-dev].
    - Can only install one of: laravel/framework[5.8.x-dev, v5.7.9].
    - don't install illuminate/support 5.8.x-dev|don't install laravel/framework v5.7.9
    - don't install illuminate/support v5.8.0|don't install laravel/framework v5.7.9
    - don't install illuminate/support v5.8.2|don't install laravel/framework v5.7.9
    - don't install illuminate/support v5.8.3|don't install laravel/framework v5.7.9
    - Installation request for laravel/framework (locked at v5.7.9, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.9].


Installation failed, reverting ./composer.json to its original content.

C:\xampp\htdocs\BMS\Mbus>

**Comment by leandromatilla** [comment]
Change laravel version in composer.json to "laravel/framework": "5.7.28",
