### ISSUE TITLE
API on user level

### ISSUE THREAD

**Issue by jozeflambrecht** [spatie/laravel-newsletter#131]
Hi,

I wrote an application to manage the memberships of a student club. I am using this package to sync the mailchimp list. Now another student club wants to use the application. How could I move the authentication config (api key, list id's) from the app level (config file) to the user level (as an attribute of the logged in user)?

**Comment by freekmurze** [comment]
The easiest way would be to just use the underlying package directly

https://github.com/drewm/mailchimp-api
