### ISSUE TITLE
Doesn't publish the config file

### ISSUE THREAD

**Issue by 3issamben** [spatie/laravel-newsletter#133]
I am trying to run the command below to publish the config file to my config directory.

`php artisan vendor:publish --provider="Spatie\Newsletter\NewsletterServiceProvider"`

And I am getting this: `Nothing to publish for tag [].`

Laravel framework version 5.1
PHP version: 5.6.23
 Spatie/laravel-newsletter version: 3.7

**Comment by freekmurze** [comment]
Duplicate of #121
