### ISSUE TITLE
How to get my configured mailchimp lists 

### ISSUE THREAD

**Issue by 3issamben** [spatie/laravel-newsletter#134]
I am able to get my mailchimp lists using the api.
`$lists = Newsletter::getApi()->get('lists');`

But I want to get a list that I have configured in my `laravel-newsletter.php`, I don't see any method in the facade that supports this.

**Comment by freekmurze** [comment]
That's indeed not supported atm. The methods available on the facade mostly revolve around subscribing someone.

The code you mention is the best way of fetching a list using this package.
