### ISSUE TITLE
Can you please give me a sample of controller?

### ISSUE THREAD

**Issue by avastamin** [spatie/laravel-newsletter#14]
I can't use this one: Newsletter::subscribe('obi-wan.kenobi@stewjon.com')

I am getting error.

**Comment by freekmurze** [comment]
Did you import the `Newsletter`-namespace in your controller?

```php
use Newsletter;
```

In future issue in this and other projects please specifiy which error you are getting. "There is an error" is pretty vague.

**Comment by avastamin** [comment]
Thank you, the error gone but getting new error: Unknown list name for mailChimp

I am trying to use  Newsletter::subscribe('example@domain.com', ['firstName' => 'firstname', 'lastName' => 'lastname'], '4756d4b4cc');

I also tried with list name but now way....

I appreciate your quick response

**Comment by freekmurze** [comment]
You can subscribe someone to a specific list by using the third argument of the `subscribe`-function:

```php
Newsletter::subscribe('rincewind@discworld.com', ['firstName'=>'Rince', 'lastName'=>'Wind'], 'subscribers');
```
That third argument is the name of a list you configured in the config file, not the mailchimp id.
