### ISSUE TITLE
subscribing members where there's additional merge fields

### ISSUE THREAD

**Issue by 1stevengrant** [spatie/laravel-newsletter#140]
Trying to do:

```
Newsletter::subscribeOrUpdate($registrant->email, [
			'FNAME' => $request->first_name,
			'LNAME' => $request->last_name,
			'VENUE' => $request->rehearsal_venue,
			'STREET' => $request->address,
			'CITY' => $request->city,
			'POSTCODE' => $request->postcode,
			'PHONE' => $request->phone,
			'VOICE' => $request->voice,
		], '2018 Choir');
```

List id and name is set in `newsletter.php` - the custom merge fields are defined in Mailchimp.

I first added just venue and that worked fine, added the others and I got nothing passed.

**Comment by freekmurze** [comment]
Put a `dd` statement somewhere in these lines to investigate what's actually being passed to mailchimp: https://github.com/spatie/laravel-newsletter/blob/master/src/Newsletter.php#L26-L28
