### ISSUE TITLE
PHP7 compatibility

### ISSUE THREAD

**Issue by remkobrenters** [spatie/laravel-newsletter#15]
First of all, thanks for this great piece of code, are you guys planning on implementing support for PHP7 (especially the issue with static calls to non-static methods).

**Comment by freekmurze** [comment]
This package should be compatible with PHP 7. What error are you getting?

**Comment by remkobrenters** [comment]
It is not strictly incompatible but static calls to non-static methods are deprecated as of PHP7. 
[http://php.net/manual/en/migration70.deprecated.php](http://php.net/manual/en/migration70.deprecated.php)

As the default implementation makes use of these calls on strict environments this will break resulting in:

`Non-static method Spatie\Newsletter\MailChimp\Newsletter::subscribe() should not be called statically`

**Comment by freekmurze** [comment]
I'll take a look at this soon. I'd accept a pull request that fixes this if you need this quick.

**Comment by remkobrenters** [comment]
Did a little testing but I’m afraid this affects a large portion of the code and I have a shortage of spare time to create a solid fix. For now a workaround for people running into this (who only need simple subscribes):

`$mailchimp = new Mailchimp(config('laravel-newsletter.mailChimp.apiKey'));`
`$mailchimp->lists->subscribe(config('laravel-newsletter.mailChimp.lists.subscribers.id'),['email' => 'test@test.tld');`

**Comment by sebastiandedeyne** [comment]
You're not supposed to call the function statically, the examples in the docs are using the facade, not the actual `Newsletter` class.

You'd either use the facade (which proxies to a non-static method):

```php
use Newsletter;

Newsletter::subscribe('rincewind@discworld.com');
```

Or resolve it from the IoC container and call the instance method:

```php
app()->make('laravel-newsletter-mailchimp')->subscribe('rincewind@discworld.com');
```

**Comment by remkobrenters** [comment]
Thanks! Very nice, than maybe a little note could be to document the right namespace definition as my IDE normally automatically detects the namespaces that should be included (and, if multiple matches are found, let's you choose the one you want) but not in this case. It will automatically select:
`use Spatie\Newsletter\MailChimp\Newsletter;`

**Comment by sebastiandedeyne** [comment]
Yeah, IDE's generally don't autocomplete facades since they don't actually exist in the codebase, but are registered via configuration.

We added the import statement to the readme for future clarity.

**Comment by remkobrenters** [comment]
Yup, normally this isn't a problem but guess the IDE got confused in this case. Thanks again.
