### ISSUE TITLE
Could not find a default list named 'xxxxx'

### ISSUE THREAD

**Issue by luisdiaswiz** [spatie/laravel-newsletter#151]
Hello,

I am trying out the package and i am having an issue, when calling the subscribe method i am getting the error Could not find a default list named 'xxxxx', xxxx being the name of the list on Mailchimp as well as the "defaultListName" parameter on the config file.

The api key is set as well the list id parameter. 

Could you please provide some help?

Regards,

Luis Dias

**Comment by freekmurze** [comment]
Try running `php artisan config:clear`.

**Comment by luisdiaswiz** [comment]
Thanks for the fast reply.

I just got it...duh me..on the config file, in the lists array i left "subscribers" as an index. Realy dumb error....

Thank you for the reply :)

**Comment by AmityTek** [comment]
I have the same error with laravel 5.7 ... i tried everything ... 
"Could not find a default list named" but my list is already created !

**Comment by BilawalGul** [comment]
AmityTek did you change the  config/newsletter file

`'defaultListName' => 'Name of Your List'`

```
> 'lists' => [
> 
>         /*
>          * This key is used to identify this list. It can be used
>          * as the listName parameter provided in the various methods.
>          *
>          * You can set it to any string you want and you can add
>          * as many lists as you want.
>          */
>         'Name of Your List' => [
> 
>             /*
>              * A MailChimp list id. Check the MailChimp docs if you don't know
>              * how to get this value:
>              * http://kb.mailchimp.com/lists/managing-subscribers/find-your-list-id.
>              */
>             'id' => env('MAILCHIMP_LIST_ID'),
>         ],
>     ],
```

**Comment by Khushal-Kakadiya** [comment]
Hello,

I'm trying to use specific list name but it's always select a default list name.

Newsletter::subscribe($borrower->email, $merge_fields, 'xxxxxxxxxxxx');

Could you please provide some help?

Regards,

Khushal
