### ISSUE TITLE
cannot install laravel newsletter

### ISSUE THREAD

**Issue by yupangestu** [spatie/laravel-newsletter#156]
`
Using version ^4.2 for spatie/laravel-newsletter
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install illuminate/support v5.6.15
    - Conclusion: don't install illuminate/support v5.6.14
    - Conclusion: don't install illuminate/support v5.6.13
    - Conclusion: don't install illuminate/support v5.6.12
    - Conclusion: don't install illuminate/support v5.6.11
    - Conclusion: don't install illuminate/support v5.6.10
    - Conclusion: don't install illuminate/support v5.6.9
    - Conclusion: don't install illuminate/support v5.6.8
    - Conclusion: don't install illuminate/support v5.6.7
    - Conclusion: don't install illuminate/support v5.6.6
    - Conclusion: don't install illuminate/support v5.6.5
    - Conclusion: don't install illuminate/support v5.6.4
    - Conclusion: don't install illuminate/support v5.6.3
    - Conclusion: don't install illuminate/support v5.6.2
    - Conclusion: don't install illuminate/support v5.6.1
    - Conclusion: don't install illuminate/support v5.6.0
    - Conclusion: don't install illuminate/support v5.5.40
    - Conclusion: don't install illuminate/support v5.5.39
    - Conclusion: don't install illuminate/support v5.5.37
    - Conclusion: don't install illuminate/support v5.5.36
    - Conclusion: don't install illuminate/support v5.5.35
    - Conclusion: don't install illuminate/support v5.5.34
    - Conclusion: don't install illuminate/support v5.5.33
    - Conclusion: don't install illuminate/support v5.5.28
    - Conclusion: don't install illuminate/support v5.5.17
    - Conclusion: don't install illuminate/support v5.5.16
    - Conclusion: don't install illuminate/support v5.5.2
    - Installation request for caffeinated/modules (locked at v4.2.1, required as ^4.1) -> satisfiable by caffeinated/modules[v4.2.1].
    - spatie/laravel-newsletter 4.2.0 requires illuminate/support ~5.5.0|~5.6.0 -> satisfiable by illuminate/support[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5
.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.2, v5.6.3, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - spatie/laravel-newsletter 4.2.1 requires illuminate/support ~5.5.0|~5.6.0 -> satisfiable by illuminate/support[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5
.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.2, v5.6.3, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - Conclusion: don't install illuminate/support v5.5.0
    - Installation request for spatie/laravel-newsletter ^4.2 -> satisfiable by spatie/laravel-newsletter[4.2.0, 4.2.1].

Installation failed, reverting ./composer.json to its original content.
`

can someone give me explanation on how to resolve this?

**Comment by freekmurze** [comment]
The error message suggest that there's a conflict with the dependencies of `caffeinated/modules`.

Take a look at the dependencies of that one and ours to figure out what the problem is.
