### ISSUE TITLE
Laravel 5.6 support ?

### ISSUE THREAD

**Issue by bestony** [spatie/laravel-newsletter#159]
Hi, I use `laravel-newsletter` in `laravel 5.6`

When i debug my code, i use tinker,and in tinker ,i always get an Notice and no respose what i want.

Here is my code what input

```
>>> use Newsletter;
>>> Newsletter::getApi();
=> DrewM\MailChimp\MailChimp {#883
     +verify_ssl: true,
   }
>>> Newsletter::getMembers();
PHP Notice:  Undefined offset: 1 in /Users/bestony/Developer/php/xxxx/vendor/drewm/mailchimp-api/src/MailChimp.php on line 337
>>> Newsletter::subscribe('my-email@my-domain.com');
PHP Notice:  Undefined offset: 1 in /Users/bestony/Developer/php/xxxx/vendor/drewm/mailchimp-api/src/MailChimp.php on line 337
```
I make sure the subscribe is ok ,because i find my email in the mailchimp list contact ,but i can't get response by my command.

I read the code ,find the 337 Line is  in the 'drewm/mailchimp-api'

**can you fix this bug for me?** 

i think i should open an issue for drewm/mailchimp-api, but i also think i should open an issue for you .

### Env
PHP
> PHP 7.1.14 (cli) (built: Feb  2 2018 08:42:59) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans

Laravel && laravel-newsletter

> "spatie/laravel-newsletter": "^4.2",
  "laravel/framework": "5.6.*",

**Comment by freekmurze** [comment]
The tests seems to indicate that the right calls are made to the underlying package by drewm. Did you define a list in the config file of our package?
