### ISSUE TITLE
Can't catch AlreadySubscribed

### ISSUE THREAD

**Issue by jannickv** [spatie/laravel-newsletter#16]
Code below seems to trow an error when someone is already subscribed... Any idea how to solve?

`try {
    Newsletter::subscribe($data['email'], ['firstName'=>$data['firstname'], 'lastName'=>$data['lastname']], 'subscribers');
} catch (Exception $e) { ... }`

<img width="1011" alt="schermafbeelding 2016-02-16 om 20 20 47" src="https://cloud.githubusercontent.com/assets/3294906/13088120/3e7edcfa-d4eb-11e5-85be-ad5ef1859844.png">

<img width="996" alt="schermafbeelding 2016-02-16 om 20 28 51" src="https://cloud.githubusercontent.com/assets/3294906/13088288/ec002c08-d4eb-11e5-8acb-4e2c88816866.png">

**Comment by freekmurze** [comment]
Did you import the Exception namespace on top of your file?

```php
use Exception;
```

Alternatively you can use this code

```php
catch(\Exception) {
...
}
```

That `\` is important.
