### ISSUE TITLE
Subscribing to my old mailchimp account

### ISSUE THREAD

**Issue by Naveedali1234** [spatie/laravel-newsletter#160]
Hello and thanks for the package.

Actually i had one mailchimp account and when i installed this package and i put the api key and list id in my .env file, everything was fine but when i wanted to use another mailchimp account and collected the api key and list id of my new account and put that in my .env file but it is still subscribing to the old mailchimp account which i used before, although i had put the new api key and list id in my .env file. Please help me out in this, what might be the issue and how to solve it?

thank you

**Comment by freekmurze** [comment]
You should clear the config cache with `php artisan config:clear`.

**Comment by Naveedali1234** [comment]
i have already did it but now when i want to show the response of subscribe method then i am only getting false. please assist me with this issue. before it was working fine but now i am getting this issue.

thank you
