### ISSUE TITLE
Newsletter::getMembers();

### ISSUE THREAD

**Issue by StanBarrows** [spatie/laravel-newsletter#161]
Hi there

With `Newsletter::getMembers();` I only receive the first 10 users. 

I read about the problem in the following issue. [StackOverFlow](https://stackoverflow.com/questions/32143586/get-all-members-from-the-mailing-list-using-mailchimp-api-3-0)

Is there any chance to receive all subscribers from a list?

Cheers, Stan

**Comment by StanBarrows** [comment]
I could figure it out. With the default request, you only receive a maximum of 10 items. That's because the count variable is set by default to 10.

```
$total =  SpatieNewsletter::getMembers()['total_items'];

$parameters = ['count' => $total];

$members = SpatieNewsletter::getMembers($string = '', $parameters)['members'];
```

**Comment by driade** [comment]
@StanBarrows In fact, what is worse, it seems there's a hard limit on Mailchimp of up to 1500 results. If your list has more members, you should paginate the results using "offset".

**Comment by driade** [comment]
I also think this should be documented. I'm going to open an issue regarding this.
