### ISSUE TITLE
Non-Static Method error

### ISSUE THREAD

**Issue by GigaMick** [spatie/laravel-newsletter#162]
I'm trying to use this as it looks excellent, but I am adding this code to my controller:

```
use Newsletter;
 Newsletter::subscribe($emailaddress, ['VERIFYCODE' => $confirmation_code]);
```

and I am getting this error:

```
Non-static method 'subscribe' should not be called statically less... (⌃F1) 
Dynamic class method called as static.
```

If I try to do what the IDE is guiding me to do I end up with this:

```
$foo = new Newsletter($mailChimp, $lists);
$foo->subscribe($email);
```

But this doesn't seem to work either, I have replaced $mailChimp and $lists with my MailChimp API key and list id.

**Comment by aaposthumus** [comment]
Yeah, this confused me as well. I ended up doing:

```
use Spatie\Newsletter\NewsletterFacade as MailChimp;

foreach (config('laravel-newsletter')['lists'] as $listName => $list) {
    $member = MailChimp::getMember('mail@test.com', $listName);
}
```

I think the documentations need a little update. :-)

**Comment by freekmurze** [comment]
Added it to the docs.

**Comment by blackipie** [comment]
update your package.... for laravel 8
