### ISSUE TITLE
Class 'NewsLetter' not found , But in routes/web.php fine

### ISSUE THREAD

**Issue by KhairulAzmi21** [spatie/laravel-newsletter#166]
I use this package on LoginController, Error says Class 'NewsLetter' not found . 

But when I use it on routes/web.php . it looks fine . 

I dont have any idea why this happen.

**Comment by achilles03anil** [comment]
use Newsletter;
Did u miss the import part ?

**Comment by KhairulAzmi21** [comment]
I pretty sure i have import that . the problem is only when i put the code on the loginController. 
if i put on web.php . its fine .
