### ISSUE TITLE
Question: How to see the "errors" array?

### ISSUE THREAD

**Issue by pmochine** [spatie/laravel-newsletter#170]
I get with Newsletter::getLastError the message 

     "400: The resource submitted could not be validated. For field-specific details, see the 'errors' array"

that does not help me of course, but I cannot find it in the docs either. So how can I see the errors array?

**Comment by sebastiandedeyne** [comment]
You can see the last error that occurred with `Newsletter::getLastError()`.

https://github.com/spatie/laravel-newsletter#handling-errors

**Comment by pmochine** [comment]
didn't you read the first sentence?

> I get with Newsletter::getLastError the message

How should I get my error array then when I'm calling it?

**Comment by sebastiandedeyne** [comment]
I don't think it's possible. The underlying package only exposes the last error. Maybe look into issues in that repo for an answer. If there's away to expose more error info, feel free to send a PR here.

https://github.com/drewm/mailchimp-api
