### ISSUE TITLE
[Question] Using this package for let users use Mailchimp with my app

### ISSUE THREAD

**Issue by dmarman** [spatie/laravel-newsletter#171]
I have a lead form collector app and I am thinking to let my users integrate Mailchimp to it.
I would need to use a different API key for each user, would it be possible to set it dynamically? or the only way to set the Mailchimp key is by the config file?

Thanks, Domingo

**Comment by geetpurwar** [comment]
Hi there,

Thanks for wonderful package. I have a similar use case where users can enter their own API key.
Let me know if thats possible.

Thanks.

**Comment by alehosaini** [comment]
Actually i need it too,
Now i'm having a software as you said it should to let our users set thier own Mailchimp APIs
so if i would to do a workaround maybe i had to use Laravel config() function
but this is a little bit confused solution
so if there is any function to solve the configuration without laravel config() function it will be more nicer

**Comment by sebastiandedeyne** [comment]
This package is a wrapper around `drewm/mailchimp-api`, so for advanced use cases like dynamic configuration, +1 on directly using that package!
