### ISSUE TITLE
Resubscribing not working

### ISSUE THREAD

**Issue by andonovn** [spatie/laravel-newsletter#172]
First of all, thanks for the package :)

In regards to the issue probably it's just me so apologies in advance!

Calling `subscribe()` on an email that's already in the list but is marked as Unsubscribed does nothing for me. So the walk-around I am using right now is to first call `delete()`, and then `subscribe()`, and that's perfectly working. The only issue I am having with this walk-around is I lose track of when the user was added on the list for the first time.

Am I missing something? Or if not, would you consider merging a PR by me which adds that functionality?

**Comment by Pablodotnet** [comment]
For this you can use subscribeOrUpdate and it works fine, if user is on the list but is unsubscribed it will subscribe him again

**Comment by virumandaliya** [comment]
Hi

When Unsubscribe from campaign email of mailchimp and selected option I do not want to receive email and submit its unsubscribe.

But After that subscribeOrUpdate is not working for resubscribe.

If you unsubscribe email by this package and use this function subscribeOrUpdate in that case it will resubscribe. What to do if I want to resubscribe anyway by this package function.

Please guide

**Comment by virumandaliya** [comment]
I have selected "No longer interested" option when unsubscribe from mailchimp campaign email.

**Comment by Pablodotnet** [comment]
You can't resubscribe people who unsubscribed from one of the mailchimp campaign email, what you can do is to do a little work-around, may be adding an option that if the subscribe with the library failed, you can present a button to send user to the mailchimp subscription configuration, you can get the URL clicking the unsubscribe button on your mailchimp campaign email and get the URL from there, it is composed by three ids and one is the user email unique id, the user should be in your mailchimp list so you can get his email unique id.

**Comment by virumandaliya** [comment]
Thanks for quick response.

I have tried by first unsubscribe from mailchimp email campaign and than I tried to access below form URL and change IDs as you said and got message that user subscribe but when I see in list its status Unsubscribe only. May be I access wrong URL to mailchimp subscription configuration?

![mail chimp](https://user-images.githubusercontent.com/3543668/45248224-0b0af300-b32c-11e8-888b-f5813d809176.png)

**Comment by Pablodotnet** [comment]
When clicking subscribe to list it says that was subscribed successfully and when you check on mailchimp list it continues unsubscribed?

**Comment by virumandaliya** [comment]
Yes its status not changed. It stay as unsubscribe

**Comment by Pablodotnet** [comment]
@virumandaliya 
I think I can't provide any other solution than that, when the subscribeOrUpdate fails we make this:
`````
Newsletter::subscribeOrUpdate($user->email, [
			'FNAME' => $user->name, 'LNAME' => $userLastName
		], 'list_name', ['interests' => $interests]);

		$error = Newsletter::getLastError();
		if ($error) {
			$pattern = '/\bwas permanently deleted\b/';
			$wasPermanentlyDeleted = preg_match($pattern, $error);
			$pattern = '/\bcompliance state\b/';
			$inComplianceState = preg_match($pattern, $error);
			if ($wasPermanentlyDeleted || $inComplianceState) {
				$user->newsletterStatus = $wasPermanentlyDeleted ? 'permanentlyDeleted' : 'compliance';
				$user->save();
			}
		} else {
			$user->newsletterStatus = 'subscribed';
			$user->save();
		}
`````

And in our frontend when the user have newsletterStatus as compliance we can get the unique_id I told you before and when it is permanentlyDeleted we tell them there is an issue with the subscription and get in contact with us to find a solution, but this is basically if someone goes to your mailchimp list on your control panel and deletes the user directly from there so that doesn't suppose to happen very often
