### ISSUE TITLE
subscribe() having issue with @hotmail tld

### ISSUE THREAD

**Issue by ahkmunna** [spatie/laravel-newsletter#173]
Thank you very much for this wonderful project!

The subscribe() method works fine but if I provide a @hotmail.com email address it won't add to the list.

Newsletter::subscribe('example@hotmail.com');

This is weird! Did I do anything wrong?

**Comment by freekmurze** [comment]
That's strange. The package doesn't do anything special with the `hotmail` domain. Please contact MailChimp's support for assistance.
