### ISSUE TITLE
GDPR question

### ISSUE THREAD

**Issue by reficul** [spatie/laravel-newsletter#174]
There is a way to use mailchimp GDPR feature whit this package?

**Comment by freekmurze** [comment]
I don't know the GDPR feature. Feel free to PR any modifications needed.

**Comment by BenSampo** [comment]
For the record, you can do this by passing a 'marketing_permissions' array into the options like the following:

```
Newsletter::subscribeOrUpdate('test@example.com', [
    'NAME' => 'John Smith',
    'PHONENO' => '0987654321',
], '', [
    'marketing_permissions' => [
        [
            'marketing_permission_id' => 'xxxxx',
            'enabled' => true,
        ]
    ],
]);
```

The easiest way I found to get the marketing permission id is to look at the successful response of an existing subscriber.
