### ISSUE TITLE
check if user subscribed a campaign

### ISSUE THREAD

**Issue by Pekinese** [spatie/laravel-newsletter#18]
I currently use the default laravel user table, what's the best way to check if a user (can be identified by e-mail adress or object) is already in a campaign? So to let only users unsubscribe a newsletter in case of they subscribed it.

**Comment by freekmurze** [comment]
Out of the box the package does not provide a method for this. However you can use `Newsletter::getApi();`  to get an instance of the api so you can call anything you want.

I'd accept a PR that adds a method to the package to easily check if a user is already subscribed to a given list.
