### ISSUE TITLE
ERROR WHEN INSTALLING /laravel-newslatter

### ISSUE THREAD

**Issue by Partabsaifzakir** [spatie/laravel-newsletter#180]
Please help me resolving this error....

ERROR: Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Conclusion: remove laravel/framework v5.3.31
    - Conclusion: don't install laravel/framework v5.3.31
    - spatie/laravel-newsletter 4.2.0 requires illuminate/support ~5.5.0|~5.6.0 -> satisfiable by illuminate/support[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - spatie/laravel-newsletter 4.2.1 requires illuminate/support ~5.5.0|~5.6.0 -> satisfiable by illuminate/support[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - spatie/laravel-newsletter 4.2.2 requires illuminate/support ~5.5.0|~5.6.0|~5.7.0 -> satisfiable by illuminate/support[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.2, v5.7.3, v5.7.4, v5.7.5].
![jkdjashdjkhajkdh](https://user-images.githubusercontent.com/37533507/45979192-c390a080-c067-11e8-8d19-1ba8f43b00f8.png)

**Comment by rodrigopeixotobr** [comment]
Hi @Partabsaifzakir .
Your Laravel version is 5.3, right?
I think the current version (4.2.2) of this package doesn support it.
You will need to update your laravel version.
Or you can install the version 3.7.0 of this package.

**Comment by Partabsaifzakir** [comment]
Dear Sir,

Thanks for ur kind response, my issue has been resolved, i was making mistake, by not adding package version when installing.

e.g:-
Latest Version: composer require spatie/laravel-newsletter
Version i need: composer require spatie/laravel-newsletter "3.3.0"

**Comment by Partabsaifzakir** [comment]
> Hi @Partabsaifzakir .
> Your Laravel version is 5.3, right?
> I think the current version (4.2.2) of this package doesn support it.
> You will need to update your laravel version.
> Or you can install the version 3.7.0 of this package.

Dear Sir,

Thanks for ur kind response, my issue has been resolved, i was making mistake, by not adding package version when installing.

e.g:-
Latest Version: composer require spatie/laravel-newsletter
Version i need: composer require spatie/laravel-newsletter "3.3.0"

**Comment by anasnawaz** [comment]
![image](https://user-images.githubusercontent.com/36500428/53681634-26205380-3d0e-11e9-95fa-ba3b04fe930d.png)
how to solve it?

**Comment by jaasaria** [comment]
same here. wanted to try this using laravel 5.7 and result to same error above.

**Comment by anasnawaz** [comment]
> same here. wanted to try this using laravel 5.7 and result to same error above.

this package does not support. you can move or update the latest version or laravel then install this package.

**Comment by alirezamaleky** [comment]
composer require spatie/laravel-newsletter
Using version ^4.3 for spatie/laravel-newsletter
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for spatie/laravel-newsletter ^4.3 -> satisfiable by spatie/laravel-newsletter[4.3.0].
    - Conclusion: remove laravel/framework v5.7.28
    - Conclusion: don't install laravel/framework v5.7.28
    - spatie/laravel-newsletter 4.3.0 requires illuminate/support ~5.8.0 -> satisfiable by laravel/framework[5.8.x-dev], illuminate/support[5.8.x-dev, v5.8.0, v5.8.2, v5.8.3, v5.8.4].
    - Can only install one of: laravel/framework[5.8.x-dev, v5.7.28].
    - don't install illuminate/support 5.8.x-dev|don't install laravel/framework v5.7.28
    - don't install illuminate/support v5.8.0|don't install laravel/framework v5.7.28
    - don't install illuminate/support v5.8.2|don't install laravel/framework v5.7.28
    - don't install illuminate/support v5.8.3|don't install laravel/framework v5.7.28
    - don't install illuminate/support v5.8.4|don't install laravel/framework v5.7.28
    - Installation request for laravel/framework (locked at v5.7.28, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.28].


Installation failed, reverting ./composer.json to its original content.

**Comment by sl0wik** [comment]
Lock version to 4.2.* and it should work fine.

In composer.json change `"spatie/laravel-newsletter": "^4.3.0"` to `"spatie/laravel-newsletter": "4.2.*"`
