### ISSUE TITLE
Always got error 404

### ISSUE THREAD

**Issue by kotakorange** [spatie/laravel-newsletter#181]
Always got this response when I tried to add subscriber
"404: The requested resource could not be found.:

**Comment by petersontubini** [comment]
I'm having the same issue.

**Comment by pixel-anovak** [comment]
You probably entered wrong lists id. 
Web lists ID is not the same as the API list id. 
You can find list API key under list settings -> List name and campaign defaults -> List ID

Hope it helps.

**Comment by stefandunn** [comment]
I'm having the same problem, tried both Web ID and API list ID. Mind you, I am getting both of those IDs from the return value of `(Newsletter::getApi()->get('lists')`.

**Comment by sebastiandedeyne** [comment]
This probably has something to do with incorrect ID's as stated above, not a package bug.

Maybe worth looking through these similar issues: https://github.com/drewm/mailchimp-api/issues?utf8=%E2%9C%93&q=is%3Aissue+404

**Comment by AxelPariss** [comment]
> You probably entered wrong lists id.
> Web lists ID is not the same as the API list id.
> You can find list API ID under list settings -> List name and campaign defaults -> List ID
> 
> Hope it helps.

Works for me (my error was I took the ID from the URL but it's not the same ^^)
