### ISSUE TITLE
subscribeOrUpdate doesn't work if user is not already subscribed/unsubscribed

### ISSUE THREAD

**Issue by mgsmus** [spatie/laravel-newsletter#182]
I have run some tests with subscribeOrUpdate and it seems it doesn't work if the contact is not on the list. 

I'm getting this error if the contact is not on the list:
**400: The resource submitted could not be validated. For field-specific details, see the 'errors' array.**

and the subscription is not happening. But it works without a problem if the contact on the list, subscribed or unsubscribed. If the user is unsubscribed, subscribes again.

I've fixed my problem like this:
```
if (Newsletter::hasMember($this->email)) {
    Newsletter::subscribeOrUpdate($this->email, $data);
} else {
    Newsletter::subscribe($this->email, $data);
}
```

If this is an intended behavior, then the method name is kinda confusing imo. I thought it works like Eloquent's _updateOrCreate_

**Comment by Pablodotnet** [comment]
Duplicate of #172 I explain there why is this happening and the workaround I implemented.

**Comment by Pablodotnet** [comment]
Do something like this to check the error
`````
Newsletter::subscribeOrUpdate($this->email, $data);
$error = Newsletter::getLastError();
if ($error) { info($error) }
`````

And post the result here, may be that user have been erased directly from the mailchimp control panel or that user have cancelled his subscription from one of the campaign emails clicking on unsubscribe link on footer.

**Comment by mgsmus** [comment]
Thank you for your response. I'll run more tests today. It seems I have a different problem. I'll write the results here.

**Comment by mgsmus** [comment]
I found my error. It seems Mailchimp does not accept null values even if it is optional. I had to clean the data array using array_filter.
