### ISSUE TITLE
Subscribe with Tags

### ISSUE THREAD

**Issue by StanBarrows** [spatie/laravel-newsletter#184]
heyho,

Is there a way to subscribe someone with Tags?

- https://mailchimp.com/help/getting-started-tags/

Cheers,
Stan

**Comment by kreierson** [comment]
Looks like you might just add tag as a merge variable?
https://developer.mailchimp.com/documentation/mailchimp/reference/lists/merge-fields/

**Comment by kreierson** [comment]
I was able to get this to work by passing in tags as the 4th argument like so:

`
Newsletter::subscribe('test@example.com',
            ['FIRST_NAME' => 'John', 'LAST_NAME' => 'Doe',
            'testlist',
            ['tags' => ['tag1', 'tag2']]
        );
`

**Comment by ssjc02** [comment]
`subscribe(string $email, array $mergeFields = [], string $listName = '', array $options = [])
`
The subscribe method accepts the above parameters. So use:

```
Newsletter::subscribe('email@example.com',[
                    'FNAME'=>'John',
                     'LNAME'=>'Doe',
                ],
                      'testlist',
                      [

                        'tags'=>['tag1','tag2'],
                ],
            );
```

**Comment by poonasor** [comment]
> `subscribe(string $email, array $mergeFields = [], string $listName = '', array $options = []) ` The subscribe method accepts the above parameters. So use:
> 
> ```
> Newsletter::subscribe('email@example.com',[
>                     'FNAME'=>'John',
>                      'LNAME'=>'Doe',
>                 ],
>                       'testlist',
>                       [
> 
>                         'tags'=>['tag1','tag2'],
>                 ],
>             );
> ```

That is not working for me, i've even tried:
`                Newsletter::subscribeOrUpdate(
                    $request->email,
                    [
                        'FNAME' => $request->name,
                        'LNAME' => $request->last_name
                    ],
                    'subscribers',
                    [
                        'tags' => [
                            'tag1' => true,
                            'tag2' => true
                        ]
                    ],
                );`
