### ISSUE TITLE
Spatie laravel-newsletter giving Undefined method error on all methods.

### ISSUE THREAD

**Issue by malik-umair** [spatie/laravel-newsletter#185]
I'm trying to use "Spatie/laravel-newsletter: 3.7.0" version. Below is my app.php:

    provider: Spatie\Newsletter\NewsletterServiceProvider::class,
    aliases: 'Newsletter' => Spatie\Newsletter\NewsletterFacade::class,

Also published vendor to generate laravel-newsletter file and set api key and list id in that.
Now in my controller, I'm unable to use any of it's method and it gives undefined errors on all method I tried to use.

    use Newsletter;
    Newsletter::isSubscribed($request->email)
    Newsletter::subscribePending($request->email);

It's giving errors that those functions are not defined.

**Comment by Giacomo92** [comment]
try `use Spatie\Newsletter\NewsletterFacade as Newsletter;` instead of `use Newsletter;` @malik-umair

**Comment by jringeisen** [comment]
I had this same issue and @Giacomo92's solution fixed it. Shouldn't this be in the documentation?

**Comment by malik-umair** [comment]
Yes it should be included in documentation. Mine issue was also fixed. Thanks @Giacomo92
