### ISSUE TITLE
Subscribe returns false

### ISSUE THREAD

**Issue by struyfv** [spatie/laravel-newsletter#186]
Hi,

When I want to subscribe an e-mail to a list, I always get false as response.

Newsletter::subscribe($input['email']);

![image](https://user-images.githubusercontent.com/13885080/49093790-291a2c80-f265-11e8-8ba9-62f9a25d51fe.png)

Any idea?

**Comment by Giacomo92** [comment]
check here https://github.com/spatie/laravel-newsletter/issues/50 and try `Newsletter::getLastError();` in order to get more information on your error.
@struyfv

**Comment by leaderaymane** [comment]
**I solved the same problem**

run this commandes :

- composer install
- php artisan config:cache
- php artisan route:cache
