### ISSUE TITLE
Non-static method Spatie\Newsletter\MailChimp\Newsletter::subscribe() should not be called statically

### ISSUE THREAD

**Issue by danmurf** [spatie/laravel-newsletter#19]
Hi,

I've recently upgraded to Laravel 5.2 and I've noticed the following errors appearing.

> Non-static method Spatie\Newsletter\MailChimp\Newsletter::subscribe() should not be called statically

I'm referencing the Newsletter with the following at the top of my controller:

`use Spatie\Newsletter\MailChimp\Newsletter;`

And it was working ok previously. Are the methods no longer defined as static? Any idea what could be causing this? Many thanks for your help

**Comment by freekmurze** [comment]
The error will melt away like snow in the sun when you replace that use statements by the facade:

```php
use Newsletter
```

**Comment by NicolasVanhecke** [comment]
`use Newsletter;` gives me 'Undefined class'. When I import the class automatically with PHPStorm it imports `use Spatie\Newsletter\Newsletter;`

**Comment by freekmurze** [comment]
@NicolasVanhecke Did you install the facade?

```php
// config/app.php
'aliases' => [
    ..
    'Newsletter' => 'Spatie\Newsletter\NewsletterFacade',
];
```

**Comment by NicolasVanhecke** [comment]
@freekmurze 
Yes,  the provider and alias has been added.. Also ran the publishing command.

**Comment by xitude** [comment]
I am also having this issue. L5.1

**Comment by tobisanya** [comment]
Any update on this. Still having this issue on L5.2

**Comment by tobisanya** [comment]
Just found a solution for this on L5.2
import at the top of your code: 
`use Spatie\Newsletter\NewsletterFacade as Newsletter;`

**Comment by GigaMick** [comment]
Sorry I realise that this is closed but @tobisanya 's solution really helped me when everything else did not (and I did try everything else!). I feel like this should be in the docs.

**Comment by xitude** [comment]
@GigaMick +1 for this to be added to the docs. @freekmurze

**Comment by techmadeeasy** [comment]
more than a year later I still faced the same issue and couldn't find it in the doc, thank you @tobisanya

**Comment by blackipie** [comment]
i am having this issue:
Non static method 'isSubscribed' should not be called statically.

**Comment by tmekfouldji** [comment]
I think the documentation is outdated,
This worked for me : 
`use Spatie\Newsletter\NewsletterFacade;
.
.
.
NewsletterFacade::subscribe($email);
`
