### ISSUE TITLE
subscribeOrUpdate() doesn't update tags

### ISSUE THREAD

**Issue by drakakisgeo** [spatie/laravel-newsletter#191]
The method subscribeOrUpdate() doesn't update tags

**Comment by dylan7778** [comment]
I'm experiencing the same issue. It seems that none of the passed parameters are updated using the SubscribeOrUpdate() method.

**Comment by jringeisen** [comment]
It appears there is a specific POST method for this in the MailChimp API. I ran into the same issue and am trying to make it work, so I am thinking about giving the `Newsletter::getApi()` a go to see if I can make it work. It would be nice if there were a function for this added to the package.

https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/tags/

**Comment by jringeisen** [comment]
Here is what I did to get it to work. I plan to work on a pull request to have this feature implemented.

`$tags = ['tags' => [['name' => 'Basic', 'status' => 'active']] ]`

 `$this->createTags($email, $listName, $tags);`

    public function createTags(string $email, string $listName = '', array $tags = [])
    {
    
        $mailChimp = Newsletter::getApi();
    
        $list = $this->findListByName($listName);
    
        $response = $mailChimp->post("/lists/{$list}/members/{$this->getSubscriberHash($email)}/tags", $tags);

        return $response;
    }

    public function getSubscriberHash($email)
    {
        $mailChimp = Newsletter::getApi();

        return $mailChimp->subscriberHash($email);
    }

    public function findListByName(string $listName)
    {
        $mailChimp = Newsletter::getApi();

        $lists = $mailChimp->get('lists');

        foreach ($lists['lists'] as $list) {
            if ($list['name'] === $listName) {
                $id = $list['id'];
            }
        }

        return $id;
    }

**Comment by freekmurze** [comment]
We recently added tagging functions to this package.

**Comment by ricar2j** [comment]
I'm trying to use Newsletter::addTags and it doesn't work it throw me that error "Call to undefined method Spatie\Newsletter\Newsletter::addTags()" please some help. thanks

**Comment by hansenconnor** [comment]
> We recently added tagging functions to this package.

Where is this documented?

**Comment by lsmith77** [comment]
it seems like the documentation was lost here https://github.com/spatie/laravel-newsletter/commit/4df637fa6ceca5d686affbe3a1d82a12f6a859fd#diff-04c6e90faac2675aa89e2176d2eec7d8

@freekmurze was this intentional?

**Comment by vlados** [comment]
You can first subscribe and then addTags
```
Newsletter::subscribeOrUpdate($validatedData['email'], [], "subscribers");
Newsletter::addTags( $tags, $validatedData['email']);
```
