### ISSUE TITLE
Proposal: Clarify the behaviour of getMember / create getAllMembers()

### ISSUE THREAD

**Issue by driade** [spatie/laravel-newsletter#193]
Hello, good morning. As noted in #161 , getMembers don't return all the results in a list, but just the 10 firsts.

According to Mailchimp this is the expected behaviour. We could also ask for more results using the "count" parameter, but it seems there's a hard limit on Mailchimp, and asking for more than 1500 results would return an error. Thus, it'd be needed to paginate the calls using the "offset" parameter.

I'd like to ask about the possibility of opening a pull request for:

- Whether clarify in this package documentation how getMembers work
- Or create a new method, something like getAllMembers, that truly downloads a whole given list.

Thanks!

**Comment by freekmurze** [comment]
Feel free to submit such a PR with tests and an updated readme. Thanks!

**Comment by driade** [comment]
Thanks, will do.
