### ISSUE TITLE
Package is not Installing on Laravel 5.7.27

### ISSUE THREAD

**Issue by adnanali1996** [spatie/laravel-newsletter#197]
Hi Sir i am using laravel framewaork 5.7.27 and i am unable to install spatie/laravel-newsletter and getting error while installing.Can you please help me and thanks in advance 
![Capture](https://user-images.githubusercontent.com/44850829/54463274-52b77f00-4794-11e9-8864-2a24bb1ed131.PNG)

**Comment by scramatte** [comment]
Hi,

I'm trying to use it with lumen 5.7.8 and I've got similar issue.
Please fix it.

Regards

**Comment by adnanali1996** [comment]
> Hi,
> 
> I'm trying to use it with lumen 5.7.8 and I've got similar issue.
> Please fix it.
> 
> Engr Adnan ALi

Hi,
when i updated my project from 5.7.27 to 5.8.4 then its working fine but was not on the laravel version 5.7.27

**Comment by colinbarstow** [comment]
Has all compatibility for <5.8 been removed completely?
Seems like that is the case looking at recent pushes, I find it strange if this is the case. What is the reasoning for it?

**Comment by byCedric** [comment]
It's not super developer-friendly to remove support for versions which are still used often. I feel that the dropped support for <5.8 should have been a major change, as this breaks existing setups with older Laravels.

In the meanwhile I would say:
1. Update your Laravel to 5.8
2. Or lock your version to `4.2.0`, this is the last one that was compatible with 5.7
