### ISSUE TITLE
SSL Certificate Problem 

### ISSUE THREAD

**Issue by joshuaziering** [spatie/laravel-newsletter#20]
`Spatie\Newsletter\Exceptions\ServiceRefusedSubscription: API call to lists/subscribe failed: SSL certificate problem: unable to get local issuer certificate in `

This problem started happening very suddenly. I'm running Ubuntu 14.04 on Forge. I tried adding the CA Cert to my SSL directory to no avail:

/etc/ssl/certs$ sudo wget http://curl.haxx.se/ca/cacert.pem

I restarted nginx after doing this. Still nothing. 

This website http://redwebturtle.blogspot.nl/2013/09/mailchimp-api-v20-ssl-error-solution.html is suggesting editing curl options but that feels like a bad idea:

curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

Any suggestions?

**Comment by freekmurze** [comment]
On first glance, this problem isn't caused by this package, but by some server configuration. If you find that this was caused by an error in the package, reopen this issue.

**Comment by joshuaziering** [comment]
I ended up solving this by installing the certificate as outlined here: 

http://askubuntu.com/questions/702882/curl-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate

**Comment by freekmurze** [comment]
Future users who are facing the same problem can use [this thread on Laracasts](https://laracasts.com/discuss/channels/servers/mailchimp-ssl-certificate-problem) to discuss the problem.
