### ISSUE TITLE
addTags function not working

### ISSUE THREAD

**Issue by ricar2j** [spatie/laravel-newsletter#205]
We recently added tagging functions to this package.

_Originally posted by @freekmurze in https://github.com/spatie/laravel-newsletter/issues/191#issuecomment-486245131_

I'm trying to use Newsletter::addTags and it doesn't work it throw me that error "Call to undefined method Spatie\Newsletter\Newsletter::addTags()" please some help. thanks

**Comment by freekmurze** [comment]
Make sure you are using the correct version of the package using composer show.

**Comment by ricar2j** [comment]
I follow your steps in your documentation for installation https://github.com/spatie/laravel-newsletter

**Comment by ricar2j** [comment]
This is the version I'm Using 4.2 for spatie/laravel-newsletter

**Comment by poonasor** [comment]
if anyone lands here looking to add tags for mailchimp, check out my fork:
https://github.com/poonasor/laravel-newsletter/tree/tags

hope it helps
