### ISSUE TITLE
Wrapper for Sendy.co in addition to Mailchimp

### ISSUE THREAD

**Issue by connecteev** [spatie/laravel-newsletter#207]
@freekmurze This is an awesome package for sending email. I love the simplicity of the APIs you've created.

However, a lot of solopreneurs are eventually faced with high bills from Mailchimp usage. Just having a large list in MailChimp (even if you aren't emailing them) can still rack up high monthly usage bills. I'm sure you face the same issue.

Enter https://sendy.co/ (I have NO affiliation with them, I am simply evaluating usage of Sendy right now). Here are some good links I found:
Why people are switching from Mailchimp to Sendy: https://marcoschwartz.com/sendy
Sendy demo: https://sendy.co/demo/autoresponders-emails?i=2&a=21
Sendy "Get started" guide: https://sendy.co/get-started

There are Laravel packages as wrappers for Sendy:
https://github.com/hocza/sendy-laravel/
https://github.com/JacobBennett/SendyPHP

However, these aren't as robust as https://github.com/spatie/laravel-newsletter
It would be cool if your package was provider agnostic (as the name suggests) and not limited to just Mailchimp. Sendy.co would be my vote for the first provider to be integrated.

**Comment by freekmurze** [comment]
I currently have no need for this myself, so I'm not going to invest my time in it. 

Feel free to fork our code and create our own driver based package.
