### ISSUE TITLE
There's no method to check subscriber has tag?

### ISSUE THREAD

**Issue by muhghazaliakbar** [spatie/laravel-newsletter#208]

**Comment by riasvdv** [comment]
You can use `Newsletter::getTags('lord.vetinari@discworld.com');` to get the tags of a member

**Comment by whoisthisstud** [comment]
I am also surprised their is no default method to get a collection of members by a tag.

**Comment by muhghazaliakbar** [comment]
@whoisthisstud You can contribute and add additional method haha
