### ISSUE TITLE
"400: Your merge fields were invalid."

### ISSUE THREAD

**Issue by ryanrca** [spatie/laravel-newsletter#213]
This had been working for the last year.  Nothing (that I know of) has been changed on our end, nor in mailchimp.

We started getting this error in unit tests with this code:
`
Newsletter::subscribe($anEmail);
\Log::info(json_encode(Newsletter::getLastError());
`
logs:
`[2019-07-31 23:42:16] testing.INFO: "400: Your merge fields were invalid."`

So, my questions are:
Q:  Is anybody else suddenly seeing this?  
Q:  How can we get more debug information?
Q:  Where / how do we set the actual fields sent to mailchimp?
Q:  Did anything change recently that may have caused this?

**Comment by ryanrca** [comment]
Totally bizarre.  This just randomly started working again.  No code or configuration changes.  
What the heck?

**Comment by riasvdv** [comment]
Glad it works again! Mailchimp is sometimes very picky on the merge fields, certainly when they're set as required on their end
