### ISSUE TITLE
This package currently forces you to use the Facade

### ISSUE THREAD

**Issue by jamiehd** [spatie/laravel-newsletter#217]
Hi,

I've been using this package and like it, however I have noticed an issue with the implementation when injecting rather than using the facade.

Since the nulldriver and newsletter class do not implement any kind of interface it is impossible to use dependency injection since there isn't a single class or interface to inject.

If you want to be able to use both the null driver and the real class and be able to switch them out then you have to use the facade. If you use the \Spatie\Newsletter\Newsletter as a dependency then this breaks when you inject the nulldriver class instead.

Would it be possible to have them both implement an interface so people not using facades can still make use of your implementation? I would be happy to look into a PR for this if you would be willing to accept it.

Thanks

**Comment by atymic** [comment]
I think this would be a great idea :)

**Comment by tentus** [comment]
For the record I'd be very much in favor of this (I had posted a related issue some months ago, https://github.com/spatie/laravel-newsletter/issues/196).

**Comment by jaketoolson** [comment]
How is something like this ignored ?! This has made testing a nightmare...
