### ISSUE TITLE
I have difficulties installing this on laravel 5.8

### ISSUE THREAD

**Issue by chambahr** [spatie/laravel-newsletter#218]
This package doesn't seem to install on laravel 5.8.3
Any help?

**Comment by atymic** [comment]
Can you give us some more context? What errors do you get?

**Comment by chambahr** [comment]
Problem 1
    - Installation request for spatie/laravel-newsletter ^4.6 -> satisfiable by spatie/laravel-newsletter[4.6.0].
    - Conclusion: remove laravel/framework v5.7.19
    - Conclusion: don't install laravel/framework v5.7.19
    - spatie/laravel-newsletter 4.6.0 requires illuminate/support ~5.8.0|~6.0.0 -> satisfiable by illuminate/support[5.8.x-dev, 6.0.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9, v6.0.0].
    - don't install illuminate/support 5.8.x-dev|don't install laravel/framework v5.7.19
    - don't install illuminate/support v5.8.0|don't install laravel/framework v5.7.19
    - don't install illuminate/support v5.8.11|don't install laravel/framework v5.7.19
    - don't install illuminate/support v5.8.12|don't install laravel/framework v5.7.19
    - don't install illuminate/support v5.8.14|don't install laravel/framework v5.7.19
    - don't install illuminate/support v5.8.15|don't install laravel/framework v5.7.19
    - don't install illuminate/support v5.8.17|don't install laravel/framework v5.7.19
    - don't install illuminate/support v5.8.18|don't install laravel/framework v5.7.19
    - don't install illuminate/support v5.8.19|don't install laravel/framework v5.7.19
    - don't install illuminate/support v5.8.2|don't install laravel/framework v5.7.19
    - don't install illuminate/support v5.8.20|don't install laravel/framework v5.7.19
    - don't install illuminate/support v5.8.22|don't install laravel/framework v5.7.19
    - don't install illuminate/support v5.8.24|don't install laravel/framework v5.7.19
    - don't install illuminate/support v5.8.27|don't install laravel/framework v5.7.19
    - don't install illuminate/support v5.8.28|don't install laravel/framework v5.7.19
    - don't install illuminate/support v5.8.29|don't install laravel/framework v5.7.19
    - don't install illuminate/support v5.8.3|don't install laravel/framework v5.7.19
    - don't install illuminate/support v5.8.30|don't install laravel/framework v5.7.19
    - don't install illuminate/support v5.8.31|don't install laravel/framework v5.7.19
    - don't install illuminate/support v5.8.32|don't install laravel/framework v5.7.19
    - don't install illuminate/support v5.8.33|don't install laravel/framework v5.7.19
    - don't install illuminate/support v5.8.34|don't install laravel/framework v5.7.19
    - don't install illuminate/support v5.8.35|don't install laravel/framework v5.7.19
    - don't install illuminate/support v5.8.4|don't install laravel/framework v5.7.19
    - don't install illuminate/support v5.8.8|don't install laravel/framework v5.7.19
    - don't install illuminate/support v5.8.9|don't install laravel/framework v5.7.19
    - don't install illuminate/support 6.0.x-dev|don't install laravel/framework v5.7.19
    - don't install illuminate/support v6.0.0|don't install laravel/framework v5.7.19
    - Installation request for laravel/framework (locked at v5.7.19, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.19].

**Comment by atymic** [comment]
You are on laravel 5.7 not 5.8

>  Installation request for laravel/framework (locked at v5.7.19, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.19].

**Comment by futzlarson** [comment]
So this requires 5.8? Is there a particular reason why? I'm on 5.6 and tend to have the "If it ain't broke, don't fix it" mentality. Also, upgrading is not painless:

https://laravel.com/docs/5.7/upgrade

https://laravel.com/docs/5.8/upgrade

**Comment by atymic** [comment]
5.6 & 5.7 are both out of bug & security support:
https://laravel.com/docs/6.x/releases#support-policy

**Comment by futzlarson** [comment]
Geez, I had no idea. What a pain.

**Comment by atymic** [comment]
I'd suggest sticking with the LTS versions if you don't plan on upgrading.
