### ISSUE TITLE
Merge Fields are wrong in Readme

### ISSUE THREAD

**Issue by gerardo15** [spatie/laravel-newsletter#22]
I thought there was a problem but then after going to the mailchimp docs, i saw that first name is FNAME and last name is LNAME

Newsletter::subscribe('rincewind@discworld.com', ['firstName'=>'Rince', 'lastName'=>'Wind']);

I don't know if you did this in purpose, like everybody just put the variables they want to send, but if not, you can save people some time by adding FNAME instead of firstName and LNAME instead of lastName in the Readme

Greetings!

**Comment by freekmurze** [comment]
Hi,

I'm so sorry that you lost time with this. I've added a little note in the readme to make things more clear. Feel free to submit a PR to the readme if you feel it could be improved more.
