### ISSUE TITLE
Double API calls when trying to catch Exception from unsubscribe method

### ISSUE THREAD

**Issue by oXg3n** [spatie/laravel-newsletter#23]
Hello,

First of all, thanks for your wrapper which is very convenient!

However, when I try to catch Exception from the unsubscribe method, 2 API calls are executed:

- 1st call, the response is: n/a (the member is correctly unsubscribed)
- 2nd call, the response is: (215) List_NotSubscribed (normal because the first one did the job)

Here is my piece of code :

```
    private function unsubscribeNewsletter($email){
       try {
            Newsletter::unsubscribe($email);
            return true;
        }catch (\Exception $e){
            Session::flash('message', "Une erreur s'est produite : ".$e->getMessage());
            return false;
        }
    }
```

And from my main method I call this private method like this:

```
       if(!$this->unsubscribeNewsletter($email)){
            return redirect()->back()->withInput();
        }
        // my work continue...
```

PS: I use this function only through a GET request (with the email in parameter)

To add further details, when I unsubscribe for the first time, only one API call is made (so it's ok). However, after registering again and trying to unsubscribe again, I get an Exception because 2 API calls are made... In addition, sometimes (rarely and randomly), I get the appropriate response (without 2 calls, so without Exception), even after subscribing / unsubscribing several times...

I don't really understand, maybe the problem is because my approach is not that good. In any case, it would be glad if you could help.

Thanks in advance.

**Comment by sebastiandedeyne** [comment]
Hmm that's weird. Your code looks good to me here. This package only does one call to Mailchimp's own library (https://github.com/spatie/laravel-newsletter/blob/master/src/MailChimp/NewsletterList.php#L76), and that function also seems to do one call (https://bitbucket.org/mailchimp/mailchimp-api-php/src/03ae0dba64d1a902fb4d76004ef12c8391ededc8/src/Mailchimp/Lists.php?at=master&fileviewer=file-view-default)

I'd suggest adding some logs throughout your own code and both package's codebases in your vendor folder to see if anything gets called twice.

**Comment by oXg3n** [comment]
Thanks for your response. I have already checked your source code and that of Mailchimp and I didn't find anything wrong. I will try to add logs in every functions called (in my own code and from the packages)... I will come back when I would have figured out what is going on.

**Comment by freekmurze** [comment]
We won't fix bugs anymore on v2 of this package.

 we just released v3 of this package which is a complete rewrite. Under the hood v3 of the MailChimp API gets used. You should probably upgrade, because v2 of MailChimp's API will be shut down by the end of this year.
