### ISSUE TITLE
Non-static method should not be called statically

### ISSUE THREAD

**Issue by GigaMick** [spatie/laravel-newsletter#232]
Apologies for raising this ticket but I cannot make this work. I cannot see anything in your documentation about setting up a facade. Here's what I have:

```
Use Spatie\Newsletter\Newsletter;
```

```
Newsletter::subscribe($request->email);
```

and here's what the IDE tells me

```
non-static method should not be called statically
```

What am I missing?

**Comment by Larstw** [comment]
Do `use Newsletter;` instead, that should make it work.

**Comment by edalzell** [comment]
Ya the docs are a bit off, if you use the facade it will work, otherwise you could pop it out of the container as well `$newsletter = app(Newsletter::class);` to do it non-statically.

**Comment by PeteJStewart** [comment]
I found the documentation and this issue slightly confusing, so I'm just posting this to clarify from my understanding.

Basically I'm pretty sure the documentation is actually incorrect, as it says you can call the methods statically via the Newletter class.

What it should probably say is the use NewsletterFacade.

i.e.

use Spatie\Newsletter\NewsletterFacade;

NewsletterFacade::subscribe($request->email);

Hope that helps anyone that comes across this issue.

**Comment by GigaMick** [comment]
Thank you!

> I found the documentation and this issue slightly confusing, so I'm just posting this to clarify from my understanding.
> 
> Basically I'm pretty sure the documentation is actually incorrect, as it says you can call the methods statically via the Newletter class.
> 
> What it should probably say is the use NewsletterFacade.
> 
> i.e.
> 
> use Spatie\Newsletter\NewsletterFacade;
> 
> NewsletterFacade::subscribe($request->email);
> 
> Hope that helps anyone that comes across this issue.
