### ISSUE TITLE
Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by liran-co** [spatie/laravel-newsletter#233]
Just upgraded to the latest version and I'm getting this error (PHP version 7.4.3)

<img width="852" alt="Screen Shot 2020-03-09 at 11 54 17 PM" src="https://user-images.githubusercontent.com/5923787/76278166-51167f00-6261-11ea-8bb8-0e92df204cc0.png">

**Comment by rajucs** [comment]
Same Problem Here. ANy one have solution?

**Comment by kobecoene** [comment]
I fixed it by changing 'ssl' in "config>newsletter.php" to false
![image](https://user-images.githubusercontent.com/50698351/84712255-70136400-af68-11ea-9fa7-e6f0c4365e65.png)

**Comment by jaddoueik1** [comment]
I am experiencing the same problem
