### ISSUE TITLE
Get error as some sort of error code rather than a string

### ISSUE THREAD

**Issue by thorlucas** [spatie/laravel-newsletter#237]
Calling `Newsletter::getLastError()` returns a string. This is suboptimal as it's not easy to parse this message in order to deliver a user-friendly response. For example:

```
"400: xxxx@xxxx.com is already a list member. Use PUT to insert or update list members."
```

That's one error message and not something I'd want to tell my users.

Is there a way to instead retrieve some sort of error number that I can provide my own custom handling for?

**Comment by tharindulucky** [comment]
@thorlucas I added a new feature addressing this issue. #245 
Let me know if you find this useful.
