### ISSUE TITLE
ErrorException: Object of class DrewM\MailChimp\MailChimp could not be converted to string

### ISSUE THREAD

**Issue by olamida** [spatie/laravel-newsletter#242]
I am currently working with laravel and I get error: 
**ErrorException: Object of class DrewM\MailChimp\MailChimp could not be converted to string** when I try to printout the lists output.

My intention is be able to create and also get and list all available lists.
How do I write to get this?
I am currently getting error when I print_r for lists

        use App\Models\Campaign;
        $api = Newsletter::getApi();
        $lists = $$api->get('lists');
        //print_r($lists); not working from here
        foreach($lists['lists'] as $list){
            $this_list_id = $list['id'];
            $this_list_name = $list['name'];
        }
        print_r($lists);

Config/newsletter.php:
![image](https://user-images.githubusercontent.com/24362092/91978504-1bd48080-ed1c-11ea-8e6e-12fbe5d964aa.png)

NewsletterController.php:
![image](https://user-images.githubusercontent.com/24362092/91978467-0eb79180-ed1c-11ea-8bc8-d021b58e6c0d.png)

vendors/spatie/laravel-newsletter/config/newsletter.php:
![image](https://user-images.githubusercontent.com/24362092/91978717-838acb80-ed1c-11ea-90d5-18c090d5f143.png)

Thank you.

**Comment by zbmowrey** [comment]
Not sure if you resolved this issue, but...
```$lists = $$api->get('lists');```
You have a variable variable here, which is attempting to convert the api class to a string and then reference a variable with that name. Remove the redundant $ from $$api and it should work.

**Comment by olamida** [comment]
Thanks @zbmowrey.

I've resolve the issue. I was having problem understanding how to use the Mailchimp API with laravel-newsletter.
The solution I used was to call the $api = Newsletter::getApi(), then follow the Mailchimp API documentation how to call the functions, the parameters and the return values, and it all worked from there.
