### ISSUE TITLE
Return value of Spatie\Newsletter\NewsletterList::getId() must be of the type string, null returned 

### ISSUE THREAD

**Issue by farshadff** [spatie/laravel-newsletter#256]
on laravel 8 i do it like below :
```
 public function store(Request $request)
    {
        Newsletter::subscribe('rincewind@discworld.com');

        return redirect('newsletter')->with('failure', 'Sorry! You have already subscribed ');

    }
``` 
but i get this error : 
![screencapture-localhost-8000-newsletter-2021-01-14-12_42_28](https://user-images.githubusercontent.com/17511289/104568979-fb231c80-5665-11eb-9e01-da3334db2901.png)

and one other question is that do i need the `Newsletter` model ??

**Comment by putrafajarh** [comment]
i got this too,
