### ISSUE TITLE
resubscribe unsubscribed mail?

### ISSUE THREAD

**Issue by shady11** [spatie/laravel-newsletter#257]
Is there any method to resubscribe mail that was unsubscribed from Mailchimp dashboard?

**Comment by dcyou** [comment]
+1 same question here

**Comment by thesea2201** [comment]
You can use `subscribeOrUpdate` function: 
`Newsletter::subscribeOrUpdate('rincewind@discworld.com');`

**Comment by dcyou** [comment]
> You can use `subscribeOrUpdate` function:
> `Newsletter::subscribeOrUpdate('rincewind@discworld.com');`

I already try this but it didn't work

**Comment by riasvdv** [comment]
Mailchimp doesn't allow resubscribing if someone unsubscribed, you have to fully delete them from your audience for that to work

**Comment by pmochine** [comment]
@riasvdv even I fully delete them from my audience with the "Data Management Tool", I cannot resubscribe them. I just don't get the email :(
