### ISSUE TITLE
No support for generic PATCH request

### ISSUE THREAD

**Issue by JeroenSchrader** [spatie/laravel-newsletter#268]
The Newsletter.php currently supports only 2 specific PATCH operations: one for setting the 'status' to 'unsubscribed' and one for updating the 'email_address' of the member. 

I want to be able to PATCH any value I want, but at the moment there's no support for it.
I come across this problem where I want to update a member's language whenever the language in my app changes, but I need to manually call the DrewM\MailChimp\MailChimp API at the moment, which is not desirable.

Current situation:
Newsletter.php:
```
    public function unsubscribe(string $email, string $listName = '')
    {
        $list = $this->lists->findByName($listName);

        $response = $this->mailChimp->patch("lists/{$list->getId()}/members/{$this->getSubscriberHash($email)}", [
            'status' => 'unsubscribed',
        ]);

        if (! $this->lastActionSucceeded()) {
            return false;
        }

        return $response;
    }

    public function updateEmailAddress(string $currentEmailAddress, string $newEmailAddress, string $listName = '')
    {
        $list = $this->lists->findByName($listName);

        $response = $this->mailChimp->patch("lists/{$list->getId()}/members/{$this->getSubscriberHash($currentEmailAddress)}", [
            'email_address' => $newEmailAddress,
        ]);

        return $response;
    }
```

Desired situation:
```
    /**
     * Update (PATCH) a mailchimp member
     *
     * @param string $email
     *   E-mail address of the member
     * @param array $attributes
     *   The list of attributes to update.
     * @param string $listName
     *    The audience (list) where the member is a part of
     *
     * @return object|false
     *   The MailChimp API response as an object OR false if unsuccesfull
     */
    public function updateMember(string $email, array $attributes, string $listName = '')
    {
        $mailChimp = $this->newsletter->getApi();

        $list = $this->lists->findByName($listName);

        $response = $this->mailChimp->patch("lists/{$list->getId()}/members/{$mailChimp->subscriberHash($email)}", 
        $attributes);
        
        return $response;
    }
```

**Comment by andrewsuzuki** [comment]
I would like this too. Want to open a pull request, since you've already basically written the method? I would just have the method signature be the same as `subscribeOrUpdate` for consistency. I think the code should be identical too except for `patch` instead of `put`.

**Comment by KnightAR** [comment]
subscribeOrUpdate sets default values that may overwrite the users information. For instance,

```
        $defaultOptions = [
            'email_address' => $email,
            'status' => 'subscribed',
            'email_type' => 'html',
        ];
```

The user could be unsubscribed or have another value then email_type. Those values are not required in the PATCH but are required in PUT. So it's reasonable for functions to be slightly different.
