### ISSUE TITLE
Send Campaigns after creation

### ISSUE THREAD

**Issue by fadifannoun** [spatie/laravel-newsletter#27]
How could I confirm the Campaigns and send them after creation?

**Comment by freekmurze** [comment]
This package does not provide a method for that out of the box. 

You can use `Newsletter::getApi` to get an instance of the [underlying api](https://github.com/drewm/mailchimp-api). The [official MailChimp docs](http://developer.mailchimp.com/documentation/mailchimp/reference/overview/) provide a listing of every available method. 

It seems that you can send a campaign [by sending a post request to this url](http://developer.mailchimp.com/documentation/mailchimp/reference/campaigns/#action-post_campaigns_campaign_id_actions_send). 

I'd accept a PR that adds a convenience method for sending campaigns to this package.
