### ISSUE TITLE
[suggestion] Optional for firstname & lastname

### ISSUE THREAD

**Issue by rebornishard** [spatie/laravel-newsletter#28]
Is that possible to add optonal coloumn for people who use fullname or custom coloumn name for their list

thanks

**Comment by freekmurze** [comment]
At the MailChimp side you can create any variable you might like. MailChimp calls these "merge variables". You can use the second parameters of the `subscribe`-method to populate the merge variables.

**Comment by rebornishard** [comment]
Hello @freekmurze 
very nice :+1: 
will you add this in readme documentation ?
btw thanks for great package sir :beers:

**Comment by freekmurze** [comment]
Glad you like it 😄
