### ISSUE TITLE
NullDriver missing?

### ISSUE THREAD

**Issue by olivervo** [spatie/laravel-newsletter#296]
According to `config/newsletter.php:7` "log" or "null" may be used to prevent calling the API directly from your environment. However, when I set the driver to "log" or "null" I receive error `class name must be a valid object or string.`

It seems `NullDriver.php` was removed in v5 yet the comment in `config/newsletter.php` is unchanged. Has anyone managed to disable the API using this method or was it removed in v5?

_Originally posted by @olivervo in https://github.com/spatie/laravel-newsletter/discussions/295_

**Comment by Braunson** [comment]
Also noticed this when migrating to v5. No info on why it was removed but I was using it.. Alternatively you can just copy the code and create the NullDriver locally..

https://github.com/spatie/laravel-newsletter/blob/4.11.0/src/NullDriver.php
