### ISSUE TITLE
Firstname and lastname at subscription

### ISSUE THREAD

**Issue by simpledev** [spatie/laravel-newsletter#3]
When we save a user in a list, the email only is saved or it is possible to save firstname and lastname?

**Comment by freekmurze** [comment]
I'll add an option to specify merge vars as soon as I have the time. If you need this quick, feel free to submit a pull request.

**Comment by freekmurze** [comment]
In version 2.0.0 of the package you can pass the needed mergeVars in the subscribe-function.
