### ISSUE TITLE
Class "api" not found

### ISSUE THREAD

**Issue by TasneemWahdan** [spatie/laravel-newsletter#303]
After upgrade from laravel 8  laravel-newsletter is not working anymore. I always get this error:
**Class "api" not found**

**Comment by Braunson** [comment]
You need to update your config, v5 now uses Drivers. See https://github.com/spatie/laravel-newsletter/blob/main/config/newsletter.php#L10

**Comment by TasneemWahdan** [comment]
Thanks Barunson,
Now I get Class "Spatie\MailcoachSdk\Mailcoach" not found :(

**Comment by TasneemWahdan** [comment]
Thanks Barunson,
I used this package on old versions and all I needed to do to make it work with laravel10 was:
1. change driver in newsletter.php to be :
                 'driver' => env('NEWSLETTER_DRIVER', Spatie\Newsletter\Drivers\MailChimpDriver::class),
2.  run:
                composer require drewm/mailchimp-api
