### ISSUE TITLE
Class mailchimp not found

### ISSUE THREAD

**Issue by aneeshvashisht** [spatie/laravel-newsletter#310]
![image](https://github.com/spatie/laravel-newsletter/assets/94676661/8217090e-2350-422e-82a7-f3cf8da59afb)

**Comment by aneeshvashisht** [comment]
I have change driver in config also. Changed mailchimp there also.

**Comment by khalid3bdallah** [comment]
I tested the package on a fresh laravel installation and I have the same issue 

<img width="715" alt="image" src="https://github.com/spatie/laravel-newsletter/assets/6986761/d95d8cf1-7728-43a1-b73d-62899bd68eb3">

The same happened when I changed the driver to MailChimp

<img width="709" alt="image" src="https://github.com/spatie/laravel-newsletter/assets/6986761/a8317be6-79bc-4592-baf8-78ac67562543">

**Comment by riverbankfinance** [comment]
Same issue here. This is after installing the mailchimp package composer require drewm/mailchimp-api

**Comment by kpwhelan** [comment]
Ran into this same issue and after opening all the the Spatie files in the vendor folder, I was able to pull this into my controller. Definitely not a "real" fix but it got it working.

**Comment by beNjiox** [comment]
To use with mailchimp you need :

1. to add this in your .env NEWSLETTER_DRIVER="Spatie\\Newsletter\\Drivers\\MailChimpDriver"
2. make sure you have the package "drewm/mailchimp-api" added to your composer dependencies
