### ISSUE TITLE
A few problems with list subscription

### ISSUE THREAD

**Issue by SimonDeDeyne** [spatie/laravel-newsletter#32]
When subscribing a user that already exists in a different list I got the following error:
400: e@mail.com is already a list member. Use PUT to insert or update list members.

In addition, using the following settings in laravel-newsletter
                'subscribe' => [
                    'emailType' => 'html',
                    'requireDoubleOptin' => true,
                    'updateExistingUser' => true,
                ],

didn't result in an double optin mail being send? 
These seemed to work fine in the previous version. Any ideas?

**Comment by freekmurze** [comment]
Have you upgraded from v2 of this package to v3? If so, there are many breaking changes:
- the config file has been changed
- methods/parameters have been changed
- underlying Mailchimp API has been updated to v3 which does a lot of things differently.

In short: everything's changed 😄 

Please review the readme of this package (and the official docs on mailchimp v3) how things are done.
