### ISSUE TITLE
NullDriver Removed in v5

### ISSUE THREAD

**Issue by kellerjmrtn** [spatie/laravel-newsletter#321]
Reopening #295 #296

The `Spatie\Newsletter\NullDriver` was removed in the v5 release (see [here](https://github.com/spatie/laravel-newsletter/compare/4.11.0...5.0.0#diff-43d584fc5000f71b6d6c96cd41f309685e0b8dbaa6d1353a1cf5721ac229b8d0)). This driver could previously be used by setting `MAILCHIMP_DRIVER` to `null` or `log` in the env for testing

The v5 newsletter.php config file still states:
```
/*
* The driver to use to interact with MailChimp API.
* You may use "log" or "null" to prevent calling the
* API directly from your environment.
*/
```
However this no longer appears to be true, setting `NEWSLETTER_DRIVER` to `null` or `log` causes errors

This can be temporarily fixed by creating your own testing driver (or copying the old one from https://github.com/spatie/laravel-newsletter/blob/4.11.0/src/NullDriver.php, as mentioned [here](https://github.com/spatie/laravel-newsletter/issues/296#issuecomment-1576948416)). However it'd be helpful to have this functionality reintroduced into the package itself.

Willing to create a PR for this, if desired

**Comment by clementmas** [comment]
I think you should PR this back in. I followed the documentation and got the same error.

Meanwhile I'm wrapping my newsletter sign up code within `if (app()->environment('production')) {}`.
