### ISSUE TITLE
Laravel 5.1 support

### ISSUE THREAD

**Issue by rebornishard** [spatie/laravel-newsletter#33]
this will be great

**Comment by freekmurze** [comment]
This package [supports L5](https://github.com/spatie/laravel-newsletter/blob/master/composer.json#L21.)

**Comment by rebornishard** [comment]
i got error on 5.1 sir

**Comment by freekmurze** [comment]
Could you please give me as much info as you can for me to reproduce the error?

**Comment by rebornishard** [comment]
current error :
need to add ::class in provider and aliases
and in import config :
$ php artisan vendor:publish --provider="Spatie\Newsletter\NewsletterServiceProvider"
Publishing complete for tag []!

btw i copy and paste it from vendor folder

error resolved after sending email to mailchimp, api is ok, but no record

**Comment by freekmurze** [comment]
If that config file doesn't get published it means that you did not register the service provider properly. How does your `config/app.php` file look like?
