### ISSUE TITLE
Invalid MailChimp API key supplied

### ISSUE THREAD

**Issue by maximusblade** [spatie/laravel-newsletter#34]
freshly installed and newly created list is giving me
there is nothing in my mailchimp column

Whoops, looks like something went wrong.

1/1
Exception in MailChimp.php line 39:
Invalid MailChimp API key supplied.

**Comment by freekmurze** [comment]
Does the output of `config('laravel-newsletter')` both the expected api key and list id?

**Comment by raresvn** [comment]
Got the same error. I have the api key and list key in the config file but when i return config('laravel-newsletter') i get this:

{
apiKey: null,
defaultListName: "subscribers",
lists: {
subscribers: {
id: null
}
}
}

**Comment by raresvn** [comment]
Solved! Changed the config file for api key and list id, to exclude env().

**Comment by freekmurze** [comment]
@maximusblade take a look at the solution by @raresvn 
If you're problem still persist reopen this issue.

**Comment by dineshg07** [comment]
try this command after  Register the service provider.

php artisan vendor:publish --provider="Skovmand\Mailchimp\MailchimpServiceProvider"

This will publish config/mailchimp.php to your config folder.

**Comment by adriangordon1231** [comment]
This is still a problem with the current version of the package

**Comment by freekmurze** [comment]
@adriangordon1231 can you try to install the package in a vanilla laravel app?

**Comment by adriangordon1231** [comment]
I posted my comment right after doing that (Laravel 5.3)

**Comment by VinvuSoftware** [comment]
I'm getting this same error, none of the above solutions seem to be working.
When I do `config('laravel-newsletter'` I get this response:
`{
  "apiKey": null,
  "defaultListName": "subscribers",
  "lists": {
    "subscribers": {
      "id": null
    }
  },
  "ssl": true
}``
I have published the config file and added the api key and list id, however they still seem te be returning null. I've tried clearing the cache too.
@dineshg07 mentioned this:
`php artisan vendor:publish --provider="Skovmand\Mailchimp\MailchimpServiceProvider"`
I tried that and my terminal told me it worked, however I couldn't find any config file that was published.

Any help would be appreciated!

**Comment by ignivamanish** [comment]
Remove env() for using API key and List ID and use genuine email id and get result ($api = Newsletter::getApi();) and Newsletter::lastActionSucceeded(); .

**Comment by focusiq** [comment]
Solution! 
To fix this, run 

php artisan config:cache 

or restart your server, whenever you make changes to your .env file.

**Comment by maurocasas** [comment]
Has this been fixed? Maybe it's because of an invalid .env format?
