### ISSUE TITLE
The use statement with non-compound name 'Newsletter' has no effect

### ISSUE THREAD

**Issue by novakben** [spatie/laravel-newsletter#35]
When trying to add `use Newsletter;` I get this error, although everything is installed. What am I missing?

`The use statement with non-compound name 'Newsletter' has no effect`

**Comment by freekmurze** [comment]
Please verify that you've installed both the service provider and the facade.

**Comment by novakben** [comment]
Nevermind, apparently it's working without adding the use Newsletter at all... It's just accessible. Maybe some update from laravel?

**Comment by sebastiandedeyne** [comment]
If you're using it somewhere that isn't in a namespace, PHP will throw a warning if you try to import it it with a `use` statement.

**Comment by novakben** [comment]
Good to know! thanks :) other then that, great code, very readable.
