### ISSUE TITLE
lastActionSucceeded is always false after subscribing

### ISSUE THREAD

**Issue by ivanvermeyen** [spatie/laravel-newsletter#36]
Hi,

When I subscribe someone to a list, I want to check if it was successful.
But no matter what method I use, the check always fails and my exception is thrown...
When I check the list @ MailChimp though, the address was in fact successfully subscribed.
With the unsubscribe method, the success methods do return `true`...
Maybe it's related to [this drewm/mailchimp-api issue](https://github.com/drewm/mailchimp-api/issues/106)?

    public function subscribe($firstName, $lastName, $email)
    {
        if ($this->newsletter->hasMember($email)) {
            throw new EmailAlreadySubscribed("[{$email}] is already subscribed to the newsletter.");
        }

        $this->newsletter->subscribe($email, [
            'FNAME' => $firstName,
            'LNAME' => $lastName
        ]);

        if ( ! $this->newsletter->lastActionSucceeded()) {
            // This always gets called
            throw new FailedToSubscribe($this->newsletter->getLastError());
        }
    }

I also tried `->getApi()->success()` and `->hasMember($email)`...

**Comment by freekmurze** [comment]
I'm assuming it is related to the issue you mentioned. Hopefully the fix in the package will be tagged soon.

**Comment by ivanvermeyen** [comment]
They tagged the fix and the issue is resolved now 👍

**Comment by freekmurze** [comment]
Thanks for reporting this and following it up! 👍
