### ISSUE TITLE
Could not find a default list named `Test`, but list exists in Mailchimp

### ISSUE THREAD

**Issue by wappka** [spatie/laravel-newsletter#40]
Installed on localhost with errors "Could not find a default list named Test", or "There is no list named `Test`".

But in Mailchimp account I can see that list. I test it on localhost, laravel-framework 5.2, laravel-newsletter 3.0.

**Comment by freekmurze** [comment]
Did you enter [a valid list id in the config file](https://github.com/spatie/laravel-newsletter/blob/master/config/laravel-newsletter.php#L36)?

**Comment by wappka** [comment]
I copied it from settings.  How can I verify it?

**Comment by wappka** [comment]
Problem solved, needed to correct config.

**Comment by rifkirinaldi** [comment]
Hi, i'm having the same issue , using laravel 5.3   laravel-newsletter 3.4 ..... i am pretty sure that i am using  correct APi and list ID

is there any other thing that i should check ?

Here are some part of my RegisterController code : 
      ` .....
        $user->name = ucwords(Input::get('name'));
        $user->email =Input::get('email');

        $user->save();

        Newsletter::subscribe($user->email, ['firstName'=>$user->name, 'lastName'=>''],'Testlist');`
