### ISSUE TITLE
Readme field names

### ISSUE THREAD

**Issue by daniel-james-lewis** [spatie/laravel-newsletter#42]
It's super minor I know, but firstName and lastName should be FNAME and LNAME as those are the actual mergefield names MailChimp requires.

**Comment by freekmurze** [comment]
Hi,

by default those names are FNAME and LNAME in Mailchimp. But those merge variables can be renamed. If you take a close look to our readme, you'll see that we've mentioned that we've renamed those defaults to `firstName` And `lastName` (those names are a tad more readable to my eyes).
