### ISSUE TITLE
Subscribe method return false everytime

### ISSUE THREAD

**Issue by prakashmalviya** [spatie/laravel-newsletter#48]
I have installed and configure API key and List ID but during below call:
Newsletter::subscribe($data['email'], [
					'firstName' => $data['first_name'],
					'lastName'  => $data['last_name']
				], 'subscribers');

I'm getting below false and when i print the dd($this->mailChimp->getLastResponse()); I'm getting below response:
array:2 [▼
  "headers" => array:26 [▼
    "url" => "https://us8.api.mailchimp.com/3.0/lists/1621af1908/members"
    "content_type" => null
    "http_code" => 0
    "header_size" => 0
    "request_size" => 0
    "filetime" => -1
    "ssl_verify_result" => 1
    "redirect_count" => 0
    "total_time" => 0.171
    "namelookup_time" => 0.109
    "connect_time" => 0.125
    "pretransfer_time" => 0.0
    "size_upload" => 0.0
    "size_download" => 0.0
    "speed_download" => 0.0
    "speed_upload" => 0.0
    "download_content_length" => -1.0
    "upload_content_length" => -1.0
    "starttransfer_time" => 0.0
    "redirect_time" => 0.0
    "redirect_url" => ""
    "primary_ip" => "*.*.*.*"
    "certinfo" => []
    "primary_port" => 443
    "local_ip" => "*.*.*.*"
    "local_port" => 54676
  ]
  "body" => false
]

Any one have idea what is the wrong with it ?

Thanks

**Comment by freekmurze** [comment]
Are you sure that you have `firstName` and `lastName` merge variables on your MailChimp list?

**Comment by prakashmalviya** [comment]
Ohh that is what exactly issue. 
Many thanks for your support and great package!!
