### ISSUE TITLE
Non-object access

### ISSUE THREAD

**Issue by Murwa** [spatie/laravel-newsletter#5]
hey @freekmurze, thanks for the library; however I'm stuck on this error
> ErrorException in NewsletterList.php line 74:
> Trying to get property of non-object

Because ```php $this->mailChimp = $app['laravel-newsletter-mailchimp']; ``` is null. Any help?

**Comment by freekmurze** [comment]
Hi, if you take a look at [this line in the service provider](https://github.com/spatie/laravel-newsletter/blob/master/src/NewsletterServiceProvider.php#L53) you'll see that the main class is bound to `laravel-newsletter` instead of `laravel-newsletter-mailchimp`.
