### ISSUE TITLE
Newsletter::subscribe Unknown error, call getLastResponse() to find out what happened. error

### ISSUE THREAD

**Issue by luan0508** [spatie/laravel-newsletter#50]
@freekmurze thanks for the package

I am getting error while trying to subscribe an email
Unknown error, call getLastResponse() to find out what happened.

When I try to call getLastResponse() it throws error
Call to undefined method Spatie\Newsletter\Newsletter::getLastResponse()

Below is my controllers function and I've checked that $email is coming correctly:
```
   public function newsletterSubscription(Request $request) {
        $email = $request->get('email');
        Newsletter::subscribe($email);
        if (Newsletter::lastActionSucceeded()){
           return Redirect::back(); 
        }
        return Newsletter::getLastError();
    }
```

Please help!

**Comment by freekmurze** [comment]
Are you running PHP 7?

**Comment by luan0508** [comment]
yes, PHP 7.0.8

**Comment by freekmurze** [comment]
Are you sure you are using `v2` of the package? The method is [clearly defined](https://github.com/spatie/laravel-newsletter/blob/master/src/Newsletter.php#L188).

**Comment by luan0508** [comment]
Yes, using getLastError() as on above code this is response that I get:
"Unknown error, call getLastResponse() to find out what happened."

**Comment by freekmurze** [comment]
Ok, I see. Our package does not have the `getLastReponse` method, it's on the [underlying mailchimp package](https://github.com/drewm/mailchimp-api/blob/master/src/MailChimp.php#L91-L94).

You could try `Newsletter::getApi()->getLastResponse();`

**Comment by luan0508** [comment]
This is the last response, but I don't understand it. (i've hidden sensitive information)
{"headers":{"url":"https:\/\/us14.api.mailchimp.com\/3.0\/lists\/xxxxxx\/members","content_type":null,"http_code":0,"header_size":0,"request_size":0,"filetime":-1,"ssl_verify_result":1,"redirect_count":0,"total_time":0.031,"namelookup_time":0,"connect_time":0.016,"pretransfer_time":0,"size_upload":0,"size_download":0,"speed_download":0,"speed_upload":0,"download_content_length":-1,"upload_content_length":-1,"starttransfer_time":0,"redirect_time":0,"redirect_url":"","primary_ip":"xx.xx.xxx.xxx","certinfo":[],"primary_port":xxx,"local_ip":"xxx.xxx.xxx.xx","local_port":xxxxx},"body":false}

**Comment by luan0508** [comment]
Reading this thread https://github.com/drewm/mailchimp-api/issues/123 drewm says You're getting no response back at all. Check that your server has a clear path out to the web - you might need to talk to your server admin.

So probably it is because I am working on a local environment.

**Comment by chenshuiluke** [comment]
@luan0508 I was getting this error on my local environment, so I just set `ssl` in newsletter.php to false:

```
    /*
     * If you're having trouble with https connections, set this to false.
     */
    'ssl' => false,
```

**Comment by leaderaymane** [comment]
**I solved the same problem**

run this commandes :

- composer install
- php artisan config:cache
- php artisan route:cache

**Comment by DanDvoracek** [comment]
For anyone stumbling on this page, make sure to NOT put a NEWSLETTER_ENDPOINT value in your .env on top of it. If you specify it empty/without a value there you might have silent mistakes too.
