### ISSUE TITLE
Update status to unsubscribe, instead of deleting the subscriber

### ISSUE THREAD

**Issue by AnhellO** [spatie/laravel-newsletter#51]
When checking the base code, I noticed that the [function performing the unsubscribing](https://github.com/spatie/laravel-newsletter/blob/master/src/Newsletter.php#L109) is deleting the current subscriber from the list, instead of updating its status. It is true that a subscriber unsubscribed by itself cannot be added back to the list, but not sure if it is a good practice to delete the subscriber, since its history won't preserve, and maybe some projects implementing this library would want to keep track of the history for its subscribing list. Also, if the subscriber is unsubscribed manually, it can be added back to the list, and its history will remain.

http://kb.mailchimp.com/lists/growth/requirements-and-best-practices-for-lists
http://kb.mailchimp.com/lists/managing-subscribers/how-to-remove-subscribers

**Comment by freekmurze** [comment]
You're right. I'd accept a PR that changes this behaviour in a non breaking way.

**Comment by amosmos** [comment]
#52 Here's one :-)

**Comment by mradamwood** [comment]
Was just looking at this. Thanks for doing @amosmos 👍

**Comment by freekmurze** [comment]
Fixed in `v3.0.6`

**Comment by drbyte** [comment]
@freekmurze @AnhellO ... would there be value in also having a `delete` method, in case that's what is actually desired?

**Comment by freekmurze** [comment]
sure, I'd accept a PR for that (with tests and an updated readme)
