### ISSUE TITLE
Require Double opt in

### ISSUE THREAD

**Issue by stefro** [spatie/laravel-newsletter#54]
Hi,

In version 2 it was possible to set a "require double opt-in" parameter. I can't find it in this (V3) release. Is it removed?

**Comment by stefro** [comment]
Well, I figured it out!

Mailchimp didn't remove it from the API V3.
Here is how you do it (in this spatie package):
just add a 4th parameter to the subscribe method like so:
```
Newsletter::subscribe($request->email, ['FNAME' => $request->firstname, 'LNAME' => $request->lastname], '', ['status' => 'pending']);
```

When Mailchimp receives the status "pendig" it will send a confirmation email (double opt-in).

**Comment by freekmurze** [comment]
👍

**Comment by ajkerfaisal** [comment]
Thanks
