### ISSUE TITLE
Language subriber

### ISSUE THREAD

**Issue by Cannonb4ll** [spatie/laravel-newsletter#73]
How can I pass along parameters to define the user's language preference inside the Subscribe function?

**Comment by freekmurze** [comment]
Merge variables can be passed as the second argument of `subscribe`

```php
Newsletter::subscribe('sam.vines@discworld.com', ['language'=>'English']);
```

Of course, you'll first need to set up some [merge variables at MailChimp](http://kb.mailchimp.com/lists/managing-subscribers/set-default-merge-values-for-a-list).

**Comment by nicolasbeauvais** [comment]
MailChimp as it's own language field that you can set in the options array:

```php
Newsletter::subscribe(
    'john@doe.com',
    ['firstName' => 'John', 'lastname' => 'Doe'],
    'subscribers',
    ['language' => app()->getLocale()]
);
```

That way you don't have to maintain your own merge field.
Source: http://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/
