### ISSUE TITLE
The package does not post to my mailchimp account.

### ISSUE THREAD

**Issue by pearl-stack** [spatie/laravel-newsletter#78]
I have included my api_key and list id so everything works fine but when i post to my account or get subscriber info using 
'''Newsletter::subscribe($email, ['firstName'=>'Nanny', 'lastName'=>'Ogg'],'subscribers') or Newsletter::getMember('mioshine2011@gmail.com'). ''' I get no response. Thanks for your quick response.

**Comment by freekmurze** [comment]
What's the output of `Newsletter::getLastError();`

**Comment by pearl-stack** [comment]
Hello, it didn't output anything. My app key and Id are correct.

**Comment by freekmurze** [comment]
I cannot recreate this issue. Seems to be working fine here (and for most users).

Please post your solution here when you find it.

**Comment by xKairu** [comment]
Experiencing something similar.

`\Newsletter::subscribeOrUpdate('kairu@team-reflex.com', ['FNAME' => 'kyle', 'UNAME' => 'kairu']);` results in: https://gist.github.com/xKairu/7b318d09073ece892c872a28f503459f

This is updating as the email address is already subscribed, and is working as the "Last Updated" timestamp in Mailchimp is updating. Using a new email results in:

`\Newsletter::subscribeOrUpdate('kairu2@team-reflex.com', ['FNAME' => 'kyle', 'UNAME' => 'kairu']);`

https://gist.github.com/xKairu/2879e81cb413101538a02a760d0b54b5

`\Newsletter::getLastError();` just returns `false` for both.

However this time it works just fine from within Tinker, but not the queued job or straight from the controller I'm using for registering users. Even making an artisan command to loop through users and subscribing them isn't subscribing the new user I've already registered, but updates the users that are already subscribed.
