### ISSUE TITLE
There is no list named `CompanyNewletter`

### ISSUE THREAD

**Issue by krunalnerikar** [spatie/laravel-newsletter#84]
Hello,

I have created list "CompanyNewletter" at MailChimp.
And Try to add user in particular group with his interest i.e. checkbox like following

`Newsletter::subscribe($user->email,['FNAME'=>$user->first_n, 'LNAME'=>$user->last_n],'CompanyNewletter',['interests'=>['interestId'=>true, 'interestId'=>true]]);`

but i got following error

`There is no list named CompanyNewletter`

**Comment by freekmurze** [comment]
Did you add `CompanyNewletter` in the `laravel-newsletter` config file?

**Comment by rifkirinaldi** [comment]
Hi, i'm having the same issue , using laravel 5.3 laravel-newsletter 3.4 ..... i am pretty sure that i am using correct APi and list ID

**is there any other thing that i should check ?**

![mailchimp api](https://user-images.githubusercontent.com/15841751/27244103-3ea1fa16-530f-11e7-8415-1912a2bc0dfa.jpg)
![mailchimpapi2](https://user-images.githubusercontent.com/15841751/27244104-3ea733a0-530f-11e7-969a-bd199a2a4570.jpg)



Here are some part of my RegisterController code :
`...............................................................................................................
`...
$user->name = ucwords(Input::get('name'));
$user->email =Input::get('email');
$user->save();
 Newsletter::subscribe($user->email, ['FNAME'=>$user->name, 'LNAME'=>''],'Testlist');`

**Comment by freekmurze** [comment]
In the config file change `subscribers` to `Testlist`
