### ISSUE TITLE
Subscribe method response return false everytime

### ISSUE THREAD

**Issue by ramzan07** [spatie/laravel-newsletter#92]
fail to insert email in list getting response false in my Newsletter.php when i output dd($this->mailChimp->getLastResponse()); It gives below Result Please have look once

array:3 [▼
  "headers" => array:26 [▼
    "url" => "https://us16.api.mailchimp.com/3.0/lists/47108f58ef/members"
    "content_type" => null
    "http_code" => 0
    "header_size" => 0
    "request_size" => 0
    "filetime" => -1
    "ssl_verify_result" => 1
    "redirect_count" => 0
    "total_time" => 0.953
    "namelookup_time" => 0.515
    "connect_time" => 0.734
    "pretransfer_time" => 0.0
    "size_upload" => 0.0
    "size_download" => 0.0
    "speed_download" => 0.0
    "speed_upload" => 0.0
    "download_content_length" => -1.0
    "upload_content_length" => -1.0
    "starttransfer_time" => 0.0
    "redirect_time" => 0.0
    "redirect_url" => ""
    "primary_ip" => "104.88.193.117"
    "certinfo" => []
    "primary_port" => 443
    "local_ip" => "192.168.10.4"
    "local_port" => 61442
  ]
  "httpHeaders" => null
  "body" => null
]

My controller method is as

````
public function store(Request $request)
    {

        Newsletter::subscribe('zain.abc@gmail.com');

        Session::flash('subscribed', 'Successfully subscribed.');
        return redirect()->back();
    }
````

Even i am not getting any Error Please Help to fix

I also Post This Question on stackoverflow but no response [https://stackoverflow.com/questions/44911181/unable-to-connect-laravel-to-mailchimp-laravel-5-4](url)

**Comment by lukecurtis93** [comment]
I am also seeing this, was working before updated to 3.6.

**Comment by ramzan07** [comment]
I have Fresh Installation and facing same issue.

**Comment by freekmurze** [comment]
I'm departing on holiday soon, so might take a while until I can work on a fix. 

I'd appreciate a PR that fixes this.

**Comment by lukecurtis93** [comment]
I've just made a fork, I'll take a look today

**Comment by lukecurtis93** [comment]
I've had a look and I think this is more a logic issue.

As far as I can tell, if you're already in the list (whether you are subscribed or not) that function will always return false.

` Newsletter::subscribe('zain.abc@gmail.com');`

Will return true on first run of this command (if the email isn't in the list)

` Newsletter::subscribe('zain.abc@gmail.com');`

Will return false if run again. We should be using 

` Newsletter::subscribeOrUpdate('zain.abc@gmail.com');`

once this has happened for the first time... it may be worth combining these two functions into one. I'm not entirely sure on the proper way to do this.

**Comment by lukecurtis93** [comment]
Mailchimp will sometimes reject emails that it thinks are fake to mailing lists.
e.g.

```
>>> Newsletter::subscribe('test@gmail.com');
=> false
>>> Newsletter::subscribe('test@lukecurtis.com');
=> [
     "id" => "96dc600426390645ed389de6266523d8",
     "email_address" => "test@lukecurtis.com",
     "unique_email_id" => "40d5ed2fae",
     "email_type" => "html",
     "status" => "subscribed",
     "merge_fields" => [
       "FNAME" => "",
       "LNAME" => "",
     ],
     ...
       ],
     ],
   ]
```

**Comment by ramzan07** [comment]
i tried even with real emails but response always false

**Comment by lukecurtis93** [comment]
Odd. I'm not seeing this, can you please post your configuration and code in full?

**Comment by ramzan07** [comment]
@freekmurze Sir you close it Is it ok now?

**Comment by LylesXwow** [comment]
I had this same issue. And found this thread by googling.
I want to add my fix if anyone else comes across this in the future.
I got a false by dd(Newsletter::subscribe($request->email)); a real email.

It would also everytime prompt a successfull on subscription message.
It appears you have to confirm your (real) email used here in your email account (accept the email coming from mailchimp) to be seen as subscribed.
A fake email I made up Alex@hansen.dk was subscribed right away and prompted the error message saying this email is already subscribed the next times.
A fake email were also dd()'d false on first attempt of writing as stated above. Most likely mailchimp scanning fake emails. I tried test@gmail.com.

So for me it was a fix to go to my email and accept the sign up.
