### ISSUE TITLE
Status always stay subscribe (static)

### ISSUE THREAD

**Issue by jigneshcitrusbug** [spatie/laravel-newsletter#98]
i'm using laravel package - "spatie/laravel-newsletter": "^3.7"

from the installed package i found , static value of status for new subscribe email 
in method getSubscriptionOptions() :
      $defaultOptions = [
            'email_address' => $email,
            'status' =>'subscribe '     //  i want set it dynamic 'pending',
            'email_type' => 'html',
        ];

**Comment by freekmurze** [comment]
Any options you pass to `$options` in `subscribe` will overwrite the default options.

https://github.com/spatie/laravel-newsletter/blob/a6210e0/src/Newsletter.php#L36
